### ISSUE TITLE
question about TestProcessSyncCommittee_PerfectParticipation

### ISSUE THREAD

**Issue by maxkaneco** [prysmaticlabs/prysm#10251]
I have a hard time understanding TestProcessSyncCommittee_PerfectParticipation. Maybe I am missing something. At the end of the test, it is checking # of balances increases is equal to params.BeaconConfig().SyncCommitteeSize. Why is it guaranteed? If the proposer is not part of the sync committee, the # of balance increases should equal to params.BeaconConfig().SyncCommitteeSize + 1? 

I found the committeeCache is generally reused between tests without calling helpers.ClearCache(). It could potentially hide some broken tests?

Thanks

**Comment by nisdas** [comment]
Hey @maxkaneco , 

Appreciate that you are looking into our tests. The reason that it is set as `params.BeaconConfig().SyncCommitteeSize` instead as `params.BeaconConfig().SyncCommitteeSize +1` is because the proposer is also a part of the sync committee. Below is a simple check that I did to confirm it. 

```diff
diff --git a/beacon-chain/core/altair/block_test.go b/beacon-chain/core/altair/block_test.go
index 021c112fb..d625fce69 100644
--- a/beacon-chain/core/altair/block_test.go
+++ b/beacon-chain/core/altair/block_test.go
@@ -78,6 +78,11 @@ func TestProcessSyncCommittee_PerfectParticipation(t *testing.T) {
        require.NoError(t, err)
        require.Equal(t, true, balances[proposerIndex] > balances[indices[0]])
 
+       for _, idx := range indices {
+               if idx == proposerIndex {
+                       t.Errorf("Proposer index is also a part of the sync committee")
+               }
+       }
        // Sync committee should have the same profits, except you are a proposer
        for i := 1; i < len(indices); i++ {
                if proposerIndex == indices[i-1] || proposerIndex == indices[i] {
```

The reason this holds for all test runs is because we use a deterministic genesis state therefore for each iteration of our test the same exact state and shuffling is used here. You are correct that it is not guaranteed that this will always hold true, with a larger validator set, the check would more often than not be `params.BeaconConfig().SyncCommitteeSize +1` instead. 

However given that the state is deterministic along with the shuffling in the context of the test, it is guaranteed that the value will always be `params.BeaconConfig().SyncCommitteeSize `.

> I found the committeeCache is generally reused between tests without calling helpers.ClearCache(). It could potentially hide some broken tests?

That would be correct, we should be having a per test cleanup in regards to the cache here and for other tests.  Tagging @terencechain here too, as he has written this originally.

**Comment by maxkaneco** [comment]
Thanks for replying. That makes sense! I did some refactoring, which makes the eth1data fixed thus the seed. This causes the cache lookups in tests to hit when they used to miss.  Many tests are failing due to this. It appears a modularized cache is preferred.

**Comment by nisdas** [comment]
> This causes the cache lookups in tests to hit when they used to miss. Many tests are failing due to this. It appears a modularized cache is preferred.

A modularized cache would be preferred rather than the global one that we do have now, but it is difficult to do mainly because of how our core code is currently structured.

**Comment by terencechain** [comment]
Feel free to reopen the issue if there are still any unanswered questions
