### ISSUE TITLE
Improbable Race Condition on latestEth1Data

### ISSUE THREAD

**Issue by z3n-chada** [prysmaticlabs/prysm#10531]
# 🐞 Bug Report

### Description
There is an improbable race condition between the powchain and proposer service. From the proposer perspective [BlockByTimestamp](https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/powchain/block_reader.go#L117) reads more than one entry from the latestEth1Header without making a copy or locking the structure.

        latestBlkHeight := s.latestEth1Data.BlockHeight
	latestBlkTime := s.latestEth1Data.BlockTime

While the powchain service also writes to this structure in another routine without a lock [here](https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/powchain/service.go#L638).

	s.latestEth1Data.BlockHeight = header.Number.Uint64()
	s.latestEth1Data.BlockHash = header.Hash().Bytes()
	s.latestEth1Data.BlockTime = header.Time

In an improbable case we could have latestBlkHeight and latestBlkTime referring to two different blocks.

### Has this worked before in a previous version?
Unsure

## 🔬 Minimal Reproduction
N/A. Conceptual Issue.
## 🔥 Error

<pre><code>
N/A
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
linux x86_64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
kiln
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by nisdas** [comment]
Thanks for the report here, it is a definitely probably although unlikely edge case. The reason we don't have a lock when writing to it is because everything in our `powchain` service runs on a single event loop, so no multithreaded access is possible there. However `BlockByTimeStamp` is used by external services and the method can be called at anytime. The appropriate thing to do would be to lock it here.
