### ISSUE TITLE
Is it possible to run multiple execution clients against one prysm?

### ISSUE THREAD

**Issue by zzh1996** [prysmaticlabs/prysm#11289]
# 💎 Issue

I'm currently running multiple execution clients (geth, erigon, etc) on the same machine. I want these execution clients to share the same prysm to avoid (disk, memory, network, cpu) redundancy. I searched on the Internet (also prysm documentation) but found nobody talking about this approach.

If possible, how can I do this?

If not possible, please treat this as a feature request.

Also, does any other consensus client support this?

**Comment by ptxptx2** [comment]
I would think it's not possible because the beacon chain has to point to an execution client endpoint - and only one execution client can be listening to a specific endpoint.

If you are talking about just running 2 execution clients and then have prysm beacon chain point to one of them such that only the execution client pointed to would be doing actual execution, I would think that's possible.  The other one (not pointed to) would just be idle and serve as backup?

Just my 2 cents...

**Comment by rauljordan** [comment]
Hi @zzh1996 this technically possible but not something that is supported in Prysm today or in other consensus clients as far as we are aware. After the merge, each execution client needs one consensus client. It is a model of 1 Prysm : 1 Geth, but you could do 1 Prysm : N Geth if you had some kind of connection multiplexer in-between that sends the same data from Prysm to your N geth instances.

We don't recommend the above for redundancy because at the end of the day, you only have 1 Prysm instance and if that goes down, your redundancy did not matter. Unless you are operating something like Infura or an API provider, I would not recommend going down this approach. You will not gain much redundancy for the effort needed. Happy to chat more about this in our Discord [here](https://discord.gg/prysmaticlabs) to have a discussion on how to help your needs

**Comment by jackyzhujiale** [comment]
@zzh1996 seems nimbus support this feature. https://nimbus.guide/web3-backup.html
Also per Execution API doc this should be possible: https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#load-balancing-and-advanced-configurations

**Comment by nisdas** [comment]
@zzh1996 So post-merge, having a fallback will fail in its purpose. Each fallback execution node needs to be able to keep in sync with the tip of the execution chain, without a beacon node that it isnt possible. The nimbus doc states:
```
The backup web3 provider must use the same JWT secret as the main provider, and will not be used until the main provider has failed. This may result in a gap in duties as the backup provider syncs. 
```
So even if you fallback, you might need to wait a while ( depending on when your fallback was last synced) , to be back up. If you really need to have a single beacon node drive multiple execution nodes, you can take a look at this project:
https://github.com/TennisBowling/executionbackup

It provides a piece of middleware which handles this. An obvious caveat is that if your execution nodes differ from each your beacon node can be stuck, act in wierd ways.
