### ISSUE TITLE
`/eth/v1/validator/duties/sync/<epoch>` fails when requested at beginnings of epochs

### ISSUE THREAD

**Issue by moshe-blox** [prysmaticlabs/prysm#11352]
# 🐞 Bug Report

### Description

When requesting `/eth/v1/validator/duties/sync/<epoch>` around the beginning of the requested epoch (first 6-12 seconds or so), Prysm returns a 500 error. This happens on both prater & mainnet. Not sure if it's consistent, but it's reproducible on most prater epochs.

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: v2.1.4

## 🔥 Error

Reproduce:
1. Wait for the first slot of epoch X
2. `POST /eth/v1/validator/duties/sync/<X>` with a JSON array of validator indices (in my case ~2500 indices)
3. Try again if it succeeds (there's a short window of a few seconds  at the beginning of the epoch)

Response:

```json
{"message":"Could not get sync committee state: requested slot number is higher than head slot number","code":500}
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 22.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v3.0.0
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rkapka** [comment]
This behavior is expected and it also occurs on 2.1.4 (I just tested it). When you ask for sync committee duties for the current epoch (or a later one), we retrieve the state at slot 0 of the current epoch as part of processing. When you issue the request very early in an epoch, the head state hasn't been updated yet, and that's why you get this error.
