### ISSUE TITLE
unable to continue the checkpoint sync: could not get ancestor state

### ISSUE THREAD

**Issue by apiscerena** [prysmaticlabs/prysm#11525]
How to restart and continue the sync procedure?
`
10月 01 09:17:56 yang systemd[1]: Started eth consensus layer beacon chain service.

10月 01 09:17:58 yang prysm.sh[3170]: Latest Prysm version is v3.1.1.
10月 01 09:17:58 yang prysm.sh[3170]: Beacon chain is up to date.
10月 01 09:17:58 yang prysm.sh[3170]: Verifying binary integrity.
10月 01 09:17:59 yang prysm.sh[3170]: beacon-chain-v3.1.1-linux-amd64: OK
10月 01 09:18:00 yang prysm.sh[3170]: gpg: Signature made 2022年09月10日 星期六 04时57分35秒 CST
10月 01 09:18:00 yang prysm.sh[3170]: gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
10月 01 09:18:00 yang prysm.sh[3170]: gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
10月 01 09:18:00 yang prysm.sh[3170]: gpg: WARNING: This key is not certified with a trusted signature!
10月 01 09:18:00 yang prysm.sh[3170]: gpg:          There is no indication that the signature belongs to the owner.
10月 01 09:18:00 yang prysm.sh[3170]: Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
10月 01 09:18:00 yang prysm.sh[3170]: Verified /home/yang/prysm/dist/beacon-chain-v3.1.1-linux-amd64 has been signed by Prysmatic Labs.
10月 01 09:18:00 yang prysm.sh[3170]: Starting Prysm beacon-chain --mainnet --checkpoint-sync-url=https://beaconstate.info --genesis-beacon-api-url=https://beaconstate.info --execution-endpoint=http://localhost:8551 --jwt-secret=/secrets/jwtsecret --suggested-fee-recipient=0x5fa1dd7f6DCE7066d8be8B8787575d66a20Dc44C --accept-terms-of-use
10月 01 09:18:00 yang prysm.sh[3170]: time="2022-10-01 09:18:00" level=info msg="Finished reading JWT secret from /secrets/jwtsecret"
10月 01 09:18:00 yang prysm.sh[3170]: time="2022-10-01 09:18:00" level=warning msg="Running on Ethereum Mainnet" prefix=flags
10月 01 09:18:00 yang prysm.sh[3170]: time="2022-10-01 09:18:00" level=info msg="Checking DB" database-path="/home/yang/.eth2/beaconchaindata" prefix=node
10月 01 09:18:00 yang prysm.sh[3170]: time="2022-10-01 09:18:00" level=info msg="Opening Bolt DB at /home/yang/.eth2/beaconchaindata/beaconchain.db" prefix=db
10月 01 09:18:02 yang prysm.sh[3170]: time="2022-10-01 09:18:02" level=warning msg="database contains genesis with htr=0x7e76880eb67bbdc86250aa578958e9d0675e64e714337855204fb5abaaf82c2b, ignoring remote genesis state parameter"
10月 01 09:18:02 yang prysm.sh[3170]: time="2022-10-01 09:18:02" level=warning msg="origin checkpoint root 0x7d0b57cec71ffd48ff34ebe05bd6e3eb94145d52cb58c6cf8bbe5df2e8643089 found in db, ignoring checkpoint sync flags"
10月 01 09:18:02 yang prysm.sh[3170]: time="2022-10-01 09:18:02" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
10月 01 09:18:03 yang prysm.sh[3170]: time="2022-10-01 09:18:03" level=error msg="could not get ancestor state: slot 4809407 not in db due to checkpoint sync: cannot retrieve data for slot" prefix=main
`

**Comment by terencechain** [comment]
Please reopen if the issue still persists

**Comment by leafan** [comment]
same issue:
clear the db path, and start the program with flags: --checkpoint-sync-url=https://sync.invis.tools --genesis-beacon-api-url=https://sync.invis.tools which copied from here: "https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync#option-1-configure-checkpoint-sync-via-network-request", it shows me error:

[2023-09-15 18:16:24]  WARN flags: Running on Ethereum Mainnet
[2023-09-15 18:16:24]  WARN node: In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient).
[2023-09-15 18:16:24]  INFO node: Checking DB database-path=/root/.eth2/beaconchaindata
[2023-09-15 18:16:24]  INFO db: Opening Bolt DB at /root/.eth2/beaconchaindata/beaconchain.db
[2023-09-15 18:16:24]  **WARN database contains genesis with htr=0x7e76880eb67bbdc86250aa578958e9d0675e64e714337855204fb5abaaf82c2b, ignoring remote genesis state parameter**

and then, it will no longer output any things.

I think it's a bug: it will produce the db when there's no db file, whatever your params are.
