### ISSUE TITLE
Check all Spec Tests are Ran in Test Suite

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#11702]
# 🚀 Feature Request

## Description

Currently, our spec test suite downloads spec tests from a repository [here](https://github.com/ethereum/consensus-spec-tests/tree/master/tests) using a Bazel HTTP rule, and then we have to write manual Go tests for each test case according to the assertions required. We do this by checking all test cases under a hard-coded test directory path such as:

```
tests := readTestCases("tests/minimal/epoch_processing/capella")
for _, tt := range tests {
  runEpochProcessingTest(tt)
}
```
However, if there is a typo in the test directory path, our test will `PASS` despite us not testing anything. Instead, we should check that we read every single file inside of the spec tests repository during our test suite so that we do not forget an important case due to a typo.

**Comment by prestonvanloon** [comment]
Some of the tests handle this already, but many do not.

Example handling empty or bad paths: 
https://github.com/prysmaticlabs/prysm/blob/e49d8f2162159244b408e0fab8fd4c33ce91ca5f/testing/spectest/shared/common/ssz_static/ssz_static.go#L31-L42

Example of not handling it (empty `testFolders` slice would not run anything):
https://github.com/prysmaticlabs/prysm/blob/e49d8f2162159244b408e0fab8fd4c33ce91ca5f/testing/spectest/shared/bellatrix/operations/attestation.go#L22-L23

**Comment by prestonvanloon** [comment]
This has been fixed with a manual review of the current spectests. A more elaborate solution could be implemented, but I did not follow through on that. 

If we are still concerned about missing tests, we could have the spectests write out some metadata about which test files they used, consolidate it across all of the tests, then compare with the spec_tests data to check that all tests were consumed.
