### ISSUE TITLE
Please mark the next release as "required for validators", otherwise it may risk users missing slots when using mev-boost

### ISSUE THREAD

**Issue by metachris** [prysmaticlabs/prysm#11717]
The next Prysm release contains important changes, including a fix for incorrect builder API types encoding:

* https://github.com/prysmaticlabs/prysm/pull/11673

Until the next release, the way Prysm encodes the builder types is not conforming to the standard, and results in errors when decoding with types that enforce correctness.

In preparation for Capella and EIP4844 upgrades, mev-boost and the mev-boost-relay is being upgraded to use the [Attestant types](https://github.com/attestantio/go-eth2-client/tree/master/spec), which enforce a standard-compliant encoding:

* https://github.com/flashbots/mev-boost/pull/411

If these updates were to be rolled out to mev-boost and the relays, non-conforming payloads fail the decoding step and lead to users missing slots when using the builder API.

We propose that Prysm marks the next release as "required for validators". Doing so would allow us to toll out the changes to mev-boost and the relays after a reasonable wait period without putting Prysm users at risk of missing slots.

**Comment by prestonvanloon** [comment]
Hi @metachris, thanks for filing this issue. We discussed this a bit in discord and I wanted to summarize the conversation here for record. 

We are hesitant to mark the next release as urgent, critical, or anything other than a normal release for prysm users as an elevated release labeling must be used sparingly. However, we will make a call-out in the release notes and issue the next release as a minor release (v3.2.0) rather than a patch release to indicate that there is some change in the API payloads for the builder API requests from prysm. 

We ask that your team delays your changes in https://github.com/flashbots/mev-boost/pull/411 until the next hardfork as this be the best approach to releasing breaking changes without deprecating the current API.  If that is not possible, then we ask that your team indicates that a Prysm upgrade is a hard requirement for users to use your software since it contains changes that break existing behavior and overly communicate that to your users. 

To add some additional context for readers:
- Prior to https://github.com/prysmaticlabs/prysm/pull/11673, Prysm would omit JSON fields that were empty. 
- [Attestant data types](github.com/attestantio/go-eth2-client) have more strict validation that will reject certain Prysm payloads with missing fields. 
- If the builder API rejects these payloads, the user will either miss a block proposal entirely or failover to local block production with an unnecessary delay.

**Comment by metachris** [comment]
We are currently exploring a third way - to use the Attestant Capella types, with a fallback to the current Bellatrix(go-boost-utils) types (instead of Bellatrix(Attestant)). This should make the changes backwards-compatible with current and previous Prysm-versions.

**Comment by terencechain** [comment]
> We are currently exploring a third way - to use the Attestant Capella types, with a fallback to the current Bellatrix(go-boost-utils) types (instead of Bellatrix(Attestant)). This should make the changes backwards-compatible with current and previous Prysm-versions.

That's great to hear. Thanks @metachris !
