### ISSUE TITLE
Bazel 6

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#11799]
# 💎 Issue

### Background

Bazel 6 was released today and it has some breaking changes for the version of bazel_toolchains we are using.  

### Description

We need to update bazel_toolchains to the latest version which requires some updates to how we generate the cross-compile remote backend execution targets. 

See: https://github.com/bazelbuild/bazel-toolchains#where-is-rbe_autoconfig
See: https://github.com/prysmaticlabs/prysm/blob/ce125b763c6f0ced1e9207e157be2f53e44fcb27/tools/cross-toolchain/README.md
See: https://github.com/prysmaticlabs/prysm/issues/2849 (previous implementation of cross compile)

Step 1: Update `.bazel_version` to 6.0.0. (Use bazelisk to automatically download bazel 6 based on `.bazel_version`)
Step 2: Observe failing builds
Step 3: Update bazel-toolchains, fix everything (???), and update documentation for cross-toolchain compilation in docker sandbox or RBE with compatible backend
Step 4: Observe successful builds

**Comment by MohammadAbuzar945** [comment]
Update the `.bazel_version `file in your project to specify version 6.0.0. This will cause `bazelisk,` a tool that manages multiple versions of Bazel, to download and use Bazel 6 when you run Bazel commands.

Observe the builds in your project to see if they are failing. You may see errors or other issues that are caused by the breaking changes in `Bazel 6.`

Update `bazel_toolchains` to the latest version and make any necessary changes to your project's configuration or code to fix any issues caused by the update. You may also need to update the documentation for your project to reflect the changes made in step 3.

Observe the builds in your project again to see if they are successful. If the builds are successful, your project should be updated and ready to use with Bazel 6.

Keep in mind that updating to a new version of Bazel may introduce other changes or breaking changes that could affect your project. Be sure to carefully review the release notes for Bazel 6 and test your project thoroughly after updating to ensure that it is working as expected.

**Comment by nisdas** [comment]
We are currently running `6.2.1` in `develop` , so this issue is resolved.
