### ISSUE TITLE
Re-enable Slasher E2E Test

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#12415]
# 💎 Issue

### Background

In #12150 , we disabled our slasher e2e run as the evaluators were broken and all our test runs were failing continuously. This issue is to track the eventual re-enabling of it. As without the e2e run, issues such as #12404 end up being undetected until its too late.

**Comment by roycncn** [comment]
Hi Team, would like to have a look at in this issues. 

But I just re-enable this test, seems all good to me. May you advise the procedures to reproduce this issue?

**bazel test //testing/endtoend:go_default_test --test_output=streamed --test_filter=TestEndToEnd_Slasher_MinimalConfig**
```
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time                                                                                                                                                                                                                                                                                                                               
INFO: Analyzed target //testing/endtoend:go_default_test (0 packages loaded, 0 targets configured).                                                                                                                                                                                                                                                                                                                                   
INFO: Found 1 test target...                                                                                                                                                                                                                                                                                                                                                                                                          
INFO: From BazelWorkspaceStatusAction stable-status.txt:
fatal: No names found, cannot describe anything.
Target //testing/endtoend:go_default_test up-to-date:                                                                                                                                                                                                                                                                                                                                                                                 
  bazel-bin/testing/endtoend/go_default_test_/go_default_test                                                                                                                                                                                                                                                                                                                                                                         
INFO: Elapsed time: 0.157s, Critical Path: 0.01s                                                                                                                                                                                                                                                                                                                                                                                      
INFO: 1 process: 1 internal.                                                                                                                                                                                                                                                                                                                                                                                                          
INFO: Build completed successfully, 1 total action                                                                                                                                                                                                                                                                                                                                                                                    
//testing/endtoend:go_default_test                              (cached) PASSED in 349.8s

Executed 0 out of 1 test: 1 test passes.

```

**Comment by brightredchilli** [comment]
Hi, was looking at this for a little over the past week or so, and I think I know why this is happening, and want to share my findings and ask for help/suggestions.

The test sets up a double attestation to be sent to beacon node 0. Beacon node 0 never adds this to its slasher pool attestation feed here: https://github.com/prysmaticlabs/prysm/blob/88685bb3bd6fc9f9d8f98a8882fa3c37c526b105/beacon-chain/sync/validate_beacon_attestation.go#L115

because the validateCommitteeIndexBeaconAttestation method checks that the attestation originates from the same peer,  and returns. 

https://github.com/prysmaticlabs/prysm/blob/88685bb3bd6fc9f9d8f98a8882fa3c37c526b105/beacon-chain/sync/validate_beacon_attestation.go#L36-L38

This means that slashings can only be detected by beacon node 1.

 Most of the time, this works as both nodes alternate having an attached validator as the proposer for the slot, and so beacon node 1 gets a chance to process slashings and insert them to the block. But occasionally, beacon node 1 never gets to be the proposer until after its “too late”.  I say this in air quotes because in looking at debug statements I inserted, I do see the pattern like:

```bash
(1) time="2024-01-02 16:15:59" msg="saveHead 07c8c61a1d slot=11"
(2) time="2024-01-02 16:15:59" msg="ProcessEffectiveBalanceUpdates updated 247 to 31000000000 at slot=11"
(3) time="2024-01-02 16:16:00" msg="GetValidator at 247 head=07c8c61a1d slot=11 balance=32000000000 (07c8c)"

```

With those being debug statements I inserted at:
1. https://github.com/prysmaticlabs/prysm/blob/886d76fe7c582ac2df347b4b4c8d2be6a79b9097/beacon-chain/blockchain/head.go#L178
2. https://github.com/prysmaticlabs/prysm/blob/886d76fe7c582ac2df347b4b4c8d2be6a79b9097/beacon-chain/core/epoch/epoch_processing.go#L281
3. https://github.com/prysmaticlabs/prysm/blob/886d76fe7c582ac2df347b4b4c8d2be6a79b9097/beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go#L376

So it looks like the code does process effective balances, and the headblock hashes match up, but the wrong balance still gets returned. However, the failures consistently happen when beacon node 1 *doesn’t get to be proposer between slots 6 and 11*.

I could totally use some advice on whether I’m pursuing the right track, but currently thinking that the best fix is to lock the seed so that beacon node 1 gets a chance to propose before the evaluator checks for slashings.

**Comment by nisdas** [comment]
This is great progress @brightredchilli ! Thank your for digging into it. Your theory seems very plausible and makes perfect sense. If it is accurate then instead of this:
```
I could totally use some advice on whether I’m pursuing the right track, but currently thinking that the best fix is to lock the seed so that beacon node 1 gets a chance to propose before the evaluator checks for slashings.
```
How about sending the double attestation to both beacon nodes ? (both 0 and 1)

**Comment by brightredchilli** [comment]
Sounds good, I can try that.
