### ISSUE TITLE
Missing block proposal due to db context dead line

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12858]
After further investigation, `sidecar.beacon_block_root` used an incorrect block

```
time="2023-09-06 17:21:24" level=error msg="Failed to propose block" blockSlot=153206 error="rpc error: code = Unknown desc = could not process beacon block: could not validate blob data availability: context deadline waiting for blob sidecars: not found in db" prefix=validator pubKey=0xa8ac01fa07c8
```

**Comment by kasey** [comment]
The db error showing up here was actually due to an error wrapping bug, fixed with this pr: https://github.com/prysmaticlabs/prysm/pull/12859

I think you have some fixes coming for the real underlying issues (where blobs are not correctly saved to db before `ReceiveBlock` is called in the proposal rpc).

**Comment by terencechain** [comment]
The fix here will be using the correct HTR for `sidecar.beacon_block_root`
