### ISSUE TITLE
RPC(Beacon-API): Ensure Validity of Blobs Served from the Database

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12875]
**Description:**

When fetching blobs from the database, there's a potential risk of serving invalid blobs. This is especially concerning for endpoints like the beacon API. 

**Details:**

1. **Canonical Check**: Before serving blobs upon request, the server should verify if the blob is canonical. If it's canonical, it can serve right away.

2. **Blob-Only Requests**: There are instances where blobs may be requested without their associated blocks. In such cases, the node should validate blobs are valid before responding to the peer.

**Comment by james-prysm** [comment]
we have since updated to using a blob file store instead of db and addressed the concerns in the following ways.

> 1. Canonical Check: Before serving blobs upon request, the server should verify if the blob is canonical. If it's canonical, it can serve right away.

there is a canonical check on BlockRootsBySlot before getting from the store, everything else is from the ChainInfoFetcher 

> 2.Blob-Only Requests: There are instances where blobs may be requested without their associated blocks. In such cases, the node should validate blobs are valid before responding to the peer.

blob storage returns verified read-only blobs 

reference PRs #13245,13235
