### ISSUE TITLE
Validator proposed block with null fee-recipient while it's exiting

### ISSUE THREAD

**Issue by zixuanz-eth** [prysmaticlabs/prysm#13299]
### Describe the bug

For this validator https://beaconcha.in/slot/64f73dd16b5f4bf0d807c58843f2b46774e35276ae8495df6c1545afe8482a64 - it's chosen to propose a block while it's in `exiting` status. We noticed that the block had null address as its fee recipient.

### 🔬 Minimal Reproduction

Geth for EL, Prysm for both BN and VC. 
* Command for beacon node:
```
beacon-chain \
        --http-mev-relay http://localhost:18550 \
        --datadir=/data \
        --rpc-host=0.0.0.0 \
        --p2p-tcp-port=3919 \
        --p2p-udp-port=3303 \
        --verbosity=info \
        --monitoring-host=0.0.0.0 \
        --monitoring-port=8080 \
        --execution-endpoint=http://eth2-engine:8551 \
        --jwt-secret=/genesis/jwtsecret \
        --grpc-gateway-host=0.0.0.0 \
        --accept-terms-of-use \
        --mainnet
```
* Command for validator client:
```
validator \
        --datadir=/data \
        --monitoring-port=8081 \
        --monitoring-host=0.0.0.0 \
        --verbosity=info \
        --graffiti="" \
        --wallet-dir="/keystore/prysm/wallet" \
        --wallet-password-file="/keystore/prysm/passwords/wallet.pass" \
        --enable-slashing-protection-history-pruning \
        --validators-external-signer-url="http://localhost:9000" \
        --validators-external-signer-public-keys="http://localhost:9000/api/v1/eth2/publicKeys" \
        --mainnet \
        --beacon-rpc-provider=“rpc-1:4000,rpc-2:4000" \
        --dynamic-key-reload-debounce-interval=10s \
        --attest-timely \
        --proposer-settings-file="/keystore/prysm/proposer-settings.json" \
        --enable-builder \
        --web \
        --accept-terms-of-us
 ```
 Proposer-setting.json
 ```
{"default_config":{"fee_recipient":"0x0000000000000000000000000000000000000000","builder":{"enabled":true}},"proposer_config":{"<pubkey>":{"fee_recipient":"<non-null-address>"}, ...}
```

Not using webUI or key-manager API to configure fee-recipient

### What version of Prysm are you running? (Which release)

4.1.1

### Anything else relevant (validator index / public key)?

668690

**Comment by james-prysm** [comment]
Some additional thoughts on this

we are checking if the validator is active + pending but activating in the epoch but not checking if it's `exiting` when periodically ( each epoch) registering validators. This hasn't been anything special we changed recently, but maybe a combination of things happened.

to help confirm I want to ask whether that beacon node with the exiting validator that was proposing, did it happen to get restarted? we don't persistently save validator registrations to a DB anymore and it's just stored in memory by default.
If you restart the beacon node it will wipe out all the validator registrations on it, usually, this isn't a problem because you would just reregister at the start of the epoch before the duties are activated upon, but in this case it was exiting status so maybe it skipped registration? 

Let us know if you experienced anything like that.

also perhaps one way to avoid this in the future is to skip the validator registrations all together and use the proposer settings only on the beacon node side ( would need to discuss with others) but maybe we can just have those settings set there if you are using a validator -> beacon node one to one
