### ISSUE TITLE
Error in release v5.0.0: ApiError: forbidden: could not parse JWT token: signature is invalid

### ISSUE THREAD

**Issue by pablomendezroyo** [prysmaticlabs/prysm#13677]
### Describe the bug

Using  prysm with keymanager api mode enabled Im getting the error `ApiError: forbidden: could not parse JWT token: signature is invalid`

I wasnt getting this error in previous version. No JWT changes

### Has this worked before in a previous version?

```text
Yes it worked fine in previous version
```

### 🔬 Minimal Reproduction

1. Setup Prysm with keymanager api enabled
2. Import keystores
3. Error

### Error

```text
ApiError: forbidden: could not parse JWT token: signature is invalid
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v5.0.0

**Comment by dappnodedev** [comment]
We are using the same JWT secret and auth token as in the previous Prysm versions. For some reason, it is not working anymore. I have written a script that uses the same JWT library (github.com/golang-jwt/jwt/v4 `v4.5.0`) as you and if I input that private key it responds with the same token string that we have been using to communicate to the validator API.

However, since `v5.0.0` I get "signature is invalid" error when calling the validator API with the corresponding token

**Comment by james-prysm** [comment]
This issue should be resolved without code changes talking to dapp node. the default path for the prysm wallet was different due to changes on data-dir directory. I'll be closing next week unless further comments are added.

**Comment by james-prysm** [comment]
closing please reach out if more is needed. pathing will be reviewed as part of https://github.com/prysmaticlabs/prysm/pull/13682
