### ISSUE TITLE
Node Status Docs Use Absent Endpoint

### ISSUE THREAD

**Issue by thebeanogamer** [prysmaticlabs/prysm#14543]
### Describe the bug

The documentation for setting up a new node (https://docs.prylabs.network/docs/monitoring/checking-status)  says that there is a HTTP endpoint you can query to get connected Execution Layer nodes. Since the 5.1.1 update, this endpoint is no longer available.

We use this endpoint as part of our healthchecks, so any way to access the equivalent data would be very helpful please.

### Has this worked before in a previous version?

```text
This worked in 5.1.0
```

### 🔬 Minimal Reproduction

1. Start Prysm 5.1.1
2. ```bash
   curl http://localhost:3500/eth/v1alpha1/node/eth1/connections
   ```

### Error

```text
wget: server returned error: HTTP/1.1 404 Not Found
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

5.1.1

### Anything else relevant (validator index / public key)?

> ⚠️ The gRPC gateway has been deprecated from Prysm in this release. If you need JSON data, consider the standardized beacon-APIs.

I suspect this line from the release notes is the cause

**Comment by james-prysm** [comment]
Hi thanks for the report, it appears this is in fact due to the gRPC gateway removal, this was missed updating documentation and I will check that you should be able to  similar health checks via https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Node/getSyncingStatus. please let us know this this solves your issue, we should move towards standard APIs in these cases.

**Comment by thebeanogamer** [comment]
Ah perfect. I've swapped our monitoring over to the `getSyncingStatus` endpoint and upgrade all our nodes to 5.1.2. Thanks for your help!
