### ISSUE TITLE
Slow startup - blob cache

### ISSUE THREAD

**Issue by Chaz27** [prysmaticlabs/prysm#14569]
`INFO filesystem: Blob filesystem cache warm-up complete. elapsed=6m9.5552129s`

Is there a way to speed up this process? Some flags or something I can experiment with?

Windows with version 5.1.2

**Comment by prestonvanloon** [comment]
@Chaz27 can you tell us more about your system? Are you using a SSD? Which one? 

When was this node first synced? It sounds like the filesystem was quite slow as prysm traversed the blob storage to remove old blobs.

**Comment by kasey** [comment]
@Chaz27 to make sure I understand - in these two instance when you use the term `reboot`:
- `*Rebooting* the node after about 12 hours of running`
- `I let the node sync fully, then *rebooted* it after about 10 seconds`

Does reboot here mean reboot/restart the computer/Windows, or restarting the beacon node program? If it's the latter, I'm guessing the second fast start could be due to Windows caching filesystem data in memory.

**Comment by prestonvanloon** [comment]
@Chaz27 This might be windows specific behavior. Unfortunately, we are very limited with our knowledge of windows systems. We believe there may be something with the filesystem cache. Perhaps there is something we can do differently in Prysm for windows, but we would need an external contributor with knowledge of windows systems to be able to understand the root cause of the problem and propose a reasonable solution.

I found this page a bit helpful: https://learn.microsoft.com/en-us/windows/win32/fileio/file-caching

I don't think there is much that you can do differently... unless there is some windows setting?? Not sure, sorry!

**Comment by prestonvanloon** [comment]
@Chaz27 I just restarted my personal beacon node.

```
Oct 24 21:34:25 beacon-chain prysm.sh[60213]: time="2024-10-24 21:34:25" level=info msg="Blob filesystem cache warm-up complete." elapsed=50.003637232s prefix=filesystem  
```

This machine had 85213 directories in the blob folder.

**Comment by nmoreau** [comment]
Thank you @Chaz27 
I had the same issue on Windows and the antivirus exclusion did the trick.
Would you mind renaming the bug to make it clear this is a Windows issue.
Thanks!
