### ISSUE TITLE
what scenario will enable the  "--save-full-execution-payloads" param 

### ISSUE THREAD

**Issue by xinzhongyoumeng** [prysmaticlabs/prysm#14596]
# 💎 Issue

### Background

we want to deploy an archive node for beacon, but we don't know if we should enable the "--save-full-execution-payloads" param.

**Comment by kasey** [comment]
By default the beacon node will save each block to the db as a `BlindedBeaconBlock`. This is a beacon block where the `ExecutionPayload` is replaced with an `ExecutionPayloadHeader`, ie a value that replaces redundant data (already stored by EL) with the hash tree root of that data - withdrawals in capella and deneb, but more importantly the full list of payload transactions with the ssz root of the list of tx bytes in all forks >= bellatrix.

When a full ("unblinded") block is needed by the beacon node to answer an rpc or api request, it will query the EL using the execution engine by block number or hash found in the payload header, receiving an `ExecutionPayloadBody` which contains the data summarized in the `BlindedBeaconBlock`, allowing the two to be used to reconstruct the full `BeaconBlock`. For an archival node I would imagine the two downsides of this approach are 1) latency / overhead of making the EL requests 2) dependency on EL being synced in order to make these requests. On the second point, I'm not 100% sure if the api supports requesting blocks when the EL is fully offline with this flag on. I think it should but you may need to test it.

**Comment by xinzhongyoumeng** [comment]
ok, thank you
