### ISSUE TITLE
Unable to ssz.TreeHash empty pointer struct

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1461]
Opening this for tracking...

`ssz.TreeHash(&pointerStruct{})` throws an error. 

Is this expected? Why can't we treeHash an empty struct with pointers?

New failing condition: 
```go
{val: &pointerStruct{}, output: "0000000000000000000000000000000000000000000000000000000000000000"}
```
(Note: that is likely not the correct output for treehashing the empty pointer struct, but it throws an error to prove my point)

Related test:
https://github.com/prysmaticlabs/prysm/blob/d06f5ac16393683f8eaa70c0e30bd551b50f5262/shared/ssz/hash_test.go#L125

cc @houjieth

**Comment by houjieth** [comment]
Please assign to me. Will dig into this in this weekend.

**Comment by rauljordan** [comment]
Assigning to @houjieth

**Comment by houjieth** [comment]
I checked the code. The reason is that the encoding for nil pointer is not mentioned in the spec. I mentioned this in the comments [here](https://github.com/prysmaticlabs/prysm/blob/3dc6d3a2e68663adcab40a29c23daf3c17ed454b/shared/ssz/encode.go#L264)

Should we create an issue in the spec repo? Is it a must for us to have nil pointer in the data structure we want to encode/decode/treehash?

**Comment by rauljordan** [comment]
Can we walk the expected fields and fill them with zero values if they are nil when encoding/decoding?

**Comment by houjieth** [comment]
> Can we walk the expected fields and fill them with zero values if they are nil when encoding/decoding?

Say we are encoding a `*uint8` pointer. We need to differentiate between a nil pointer and a pointer that points to a zero value `uint8`. The encoding of zero value `uint8` is `0x00`, and the encoding for zero value `uint16` is `0x0000`, etc.. It's tricky to design the encoding output for nil pointer: If we want to decode a `*uint8` with input of `0x00`, should we decode it into a pointer that points to a zero-value `uint8`, or should we decode it into a nil pointer?

If we make an assumption that we will only use pointer for list and struct, we can solve the problem because no list or struct will have encoding like `0x00`, `0x0000`, `0x00000000`, etc. However, we are bringing customized encoding that's not mentioned in the spec. This will bring issue for cross-client communication.

The fundamental reason for this issue is the spec never thought of the case for pointer. The spec presumably treats pointer the same as reference.

I would suggest doing the following to unblock our development:
- Assume we don't use pointer for primitive data type (uintX, bool, etc.) for the data type we want to encode
- Use `0x00` as a semi-magic-number for nil pointer

Then add a todo item when we need to seriously deal with cross-client communication.

**Comment by rauljordan** [comment]
Thanks @houjieth ! Closed by #1553

**Comment by rauljordan** [comment]
@houjieth receiving this error in master:
```
failed to save block: failed to tree hash block: hash error: failed to hash field of struct: nil is not supported for input type *ethereum_beacon_p2p_v1.BeaconBlock
``` 
do you know why this may be happening?

**Comment by jiepony** [comment]
Some logic in `ssz/hash.go` needs to be tweaked as well.
I will send a PR very soon.

**Comment by houjieth** [comment]
Some logic inside `ssz/hash.go` needs to be tweaked as well.
I will open a PR very soon.
