### ISSUE TITLE
No deposit contract specified.

### ISSUE THREAD

**Issue by yahtoo** [prysmaticlabs/prysm#1921]
when I start beacon from
./beacon-chain   --datadir /home/xx/.beacon/   --rpc-port 4000   --demo-config --p2p-port 9000
[2019-03-07 10:37:40]  INFO node: Using custom parameter configuration
[2019-03-07 10:37:40]  INFO node: checking db
[2019-03-07 10:37:40] FATAL node: No deposit contract specified. Add --deposit-contract with a valud deposit contract address to start.
how can I get deposit contract ?

**Comment by IvanTheGreatDev** [comment]
Hello @yahtoo ! Thanks for using Prysm 😄  

So, in order to start a beacon-chain node you need to follow the steps listed here:
https://github.com/prysmaticlabs/prysm/issues/1565

They involve you deploying a deposit contract (the 1st command), starting the beacon chain node, and then setting up the 8 validators (followed by performing the 8 deposits) needed to begin chain start. We're currently working on this so apologies for the out of date docs.
