### ISSUE TITLE
Fix BLS to work with uncompressed format

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2857]
For BLS, if the uncompressed format is not compatible, it will cause an issue in [DecompressG2]( https://github.com/phoreproject/bls/blob/master/g2.go#L233)
This was reproduced by the [invalid_sig_new_deposit](https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/operations/deposit/deposit_minimal.yaml) deposit test, an invalid signature was in uncompressed format and `the process_deposit` function failed with:
```
could not convert bytes to signature: could not unmarshal bytes into signature: unexpected compression mode
```

**Comment by blacktemplar** [comment]
I had a look into this issue.

The sepc clearly states that only compressed format is allowed:

> ...
> Respecting bit ordering, `z` is decomposed as `(c_flag, b_flag, a_flag, x)`.
> ...
> A point in G2 is represented as a pair of 384-bit integers `(z1, z2)`. We decompose `z1` as above into `x1`, `a_flag1`, `b_flag1`, `c_flag1` and `z2` into `x2`, `a_flag2`, `b_flag2`, `c_flag2`.
>
>We require:
>
>* ...
>* `c_flag1 == 1`
>* ...

This basically says that the most significant bit must always be one which indicates that the format is compressed (see https://github.com/zkcrypto/pairing/tree/master/src/bls12_381#serialization)

Therefore, any uncompressed signature must be treated as invalid and therefore `bls_verify` should return False.

Our implementation returns an error if the signature is uncompressed. The reason why the test fails and the difference to the spec is, that in the spec there is no error thrown if the signature is invalid but the deposit is silently ignored, i.e. process_deposit returns at this point, see https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#deposits.

So to strictly follow the spec the only change needed would be to return beaconState, nil instead of returning an error in line https://github.com/prysmaticlabs/prysm/blob/4a422b13f066cbf05afec1c6eab17572d2f88a5b/beacon-chain/core/blocks/block_operations.go#L872.
