### ISSUE TITLE
Separate out attestation DB store

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3157]
As soon as an attestation gets packaged to a block, the attestation gets [deleted in the DB](https://github.com/prysmaticlabs/prysm/blob/1bac9ad9112b5fe0661a866f1f32654ea9dd69dd/beacon-chain/operations/service.go#L264). This is troublesome given any could still request for such attestation within the window of current epoch and next epoch. I suspect this has contributed to the original fork choice faultiness. The attestations need to be properly tracked for req/res and slashing. 

One way to address this is to have separate storages for 
1. attestation pool (attestations not yet included in the block) 
2. normal attestations (attestations that have contributed to fork choice and finality since last finalized epoch)

**Comment by nisdas** [comment]
Following on from #3258,

Currently we aggregate attestations on the fly, combining the bitfields and signatures to aggregate multiple attestations into a single one. However once an attestation with the same data root has been processed by the beacon node, we delete the attestation from our db.

We directly remove attestations by their data root from the db, we don't account for differing aggregation bitfields in the attestations that were processed and the ones that were deleted from the db. In networks with a small number of nodes, this wouldn't be an issue as attestations are easily gossiped to all nodes, so most attestations would be 'full' , however once networks become larger then a significant portion of attestations will not be successfully gossiped to all nodes. This will lead to the majority of attestations being 'partial' instead of 'full'. In this scenario the beacon node will have to track attestations by their data root, which validators have attested to them so far, and which validator's attestations have been processed and accounted for.

As mentioned above, separating storage out would be between the attestation pool and attestations included in a block above would be a potential solution. In addition to that we would also need a registry of attestations mapping their data root to the validators that have voted for them. This further should be demarcated into 2 categories:
1) Attestations from validators which have not been included yet
2) Attestations from validators which have been included in a block.

Using this we can verify each attestation and decide whether or not we should continue aggregating them or throw them away if they have already been included in a block or they are currently in our attestation pool.

**Comment by rauljordan** [comment]
Resolved by #3542
