### ISSUE TITLE
Explore Load Testing Beacon Nodes

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3497]
Hi all,

It would be fun and interesting to see just how spammable our beacon nodes are and see if we can find interesting endpoints, either p2p/RPC-based, which can be DDoS'ed by anyone. Granted, we can have spam controls by gRPC, we might still find that we could brick beacon nodes if we called expensive methods when we're not supposed to.

It would be useful to have this functionality as some simple tool within the Prysm repo that lets us either simulate a DoS scenario or directly load test certain parts of the beacon node.

**Comment by skillful-alex** [comment]
Monitoring/Visualization - metrics p2p_peer_count, p2p_message_recieved_total already exist. We can add metrics in the context of message types and in the context of p2p nodes (maybe this is a bad idea, because p2p nodes are dynamic). Including the metrics Count_of_MESSAGE_TYPE and Time_spent_on_MESSAGE_TYPE.
Load testing is only a separate utility, but we must understand what data to send to the node. Will it be constant data from a file that will allow exact reproduction of the behavior, or will the data be randomly generated according to the rules.

**Comment by rauljordan** [comment]
Closing this for now until we have more actionable items
