### ISSUE TITLE
ListValidatorBalances Not Working

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3844]
The ListValidatorBalances RPC call returns nothing, given it expects indices or public keys to function. We should return all balances paginated by default.

**Comment by prestonvanloon** [comment]
Some observations:
- Getting this data with no parameters returns nothing, i expected the current set of validators w/ balances. 
- Specifying only a validator index doesnt work since "epoch" is 0 / unspecified. If you set it to some large value in the future, then it works to fetch that validators balance in the head state.

Ex: `curl -X GET "https://api.prylabs.network/eth/v1alpha1/validators/balances?epoch=1000000&indices=0" -H "accept: application/json"`
