### ISSUE TITLE
Peer count numerator greater than denominator in Beacon Chain 

### ISSUE THREAD

**Issue by pjindal** [prysmaticlabs/prysm#4543]
While the chain did not crash, peers # is greater (numerator) than the available or connected peers (denominator). E.g. 12/0, 12/7, 12/6, etc.

![image](https://user-images.githubusercontent.com/26806409/72349434-88760e80-36aa-11ea-8ee8-ceb65b3b84e4.png)

**Comment by prestonvanloon** [comment]
This is a cosmetic bug. The left value is how many peers you queried in this round of sync, the right side is your current peer count.

**Comment by princesinha19** [comment]
@prestonvanloon should we remove `syncingPeers` count from here to make it less confusing?

**Comment by prestonvanloon** [comment]
This will be resolved in @farazdagi new sync rewrite.

**Comment by farazdagi** [comment]
The UI has been updated:
- the only number displayed now is that of available peers (so that user has idea on how connected the node is)
- since we have decoupled block fetching from processing, exposing which peers were used to fetch particular block the processor is working with atm is neither informative, nor strictly necessary. 
- Internally fetcher has quite a sophisticated peer selection strategy: it randomizes peers, using only certain portion of them to counter-act evil peers more effectively, sometimes even using only a single peer (also randomized, with fallbacks) - to peek ahead in cases of huge ranges of blocks w/o finality. But all this is considered and internal details and thus is not exposed on processor's screen -- as it will introduce more confusion than info.

Closing the issue, should we decide we need to know which block was fetched by how many peers, we can create another issue (or reopen this).
