### ISSUE TITLE
Can we reduce memory usage of deposits?

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#4604]
Currently, we keep all of the chain deposits in memory from start up. In my local node, this was around 130Mb. While not a significant memory impact at ~32k deposits, this will become problematic as the network scales.

![Screenshot from 2020-01-20 21-07-54](https://user-images.githubusercontent.com/7246818/72777352-424d0d80-3bca-11ea-9297-4e0471110bb1.png)

**Comment by rauljordan** [comment]
Do we need to keep these deposits around always? Could we just read them at the time we see them, add the relevant data need to the in-mem trie, and then have them be garbage collected? Thoughts @nisdas

**Comment by rauljordan** [comment]
Bump @nisdas is this still relevant?

**Comment by rauljordan** [comment]
Bump @nisdas let me know what you think

**Comment by nisdas** [comment]
Hey @rauljordan sorry missed this, we can probably write the majority of the deposits to disk , although we would have to maintain the trie in memory. But that should not be very expensive. I haven't had time to look at it in depth so someone else is welcome to look at this too. If not I can take this up when i have some free bandwidth.

**Comment by rkapka** [comment]
Please assign me to this issue.

**Comment by rkapka** [comment]
### Solution proposal
By far the largest amount of memory is required for the `Deposit.Proof` field. We currently keep all deposits (including historical) in `DepositCache.deposits` and all pending deposits (again including historical) in `DepositCache.pendingDeposits`, which means a lot of proofs are kept as well. Additionally most deposits are needlessly duplicated, bloating the memory even further. As blocks get finalized, deposits should no longer be in the pending state, but we only prune pending deposits during `POWService`'s initialization (there is also a `DepositCache.RemovePendingDeposit` function, but it's not used anywhere outside tests).
https://github.com/prysmaticlabs/prysm/blob/74101612ce1cb6a158fb4409e0ca401ad8bea209/beacon-chain/powchain/log_processing.go#L346

Pruning pending deposits after a block has been finalized will ensure that only a relatively small number of pending deposits are kept in memory at any time.

Both `deposits` and `pendingDeposits` fields are of the same `[]*dbpb.DepositContainer` type. `pendingDeposits` are used during block proposal, and so all fields of a deposit are needed in order to contruct a valid block, including the proof. On the other hand some fields of `deposits` items are never used, proof included, and because of this it makes more sense to store `deposits` as a slice of simpler structs. As an example, instead of returning the whole cached deposit to the caller and calculating the root hash, the hash itself could be cached within this struct. 

One more thing to fix is to remove the call to `depositCache.AllDepositContainers` during log processing. Because the cached deposits will no longer contain all data from the original deposits, log processing should handle processing and saving deposits internally instead of fetching cached deposits every `eth1DataSavingInterval`.
https://github.com/prysmaticlabs/prysm/blob/74101612ce1cb6a158fb4409e0ca401ad8bea209/beacon-chain/powchain/log_processing.go#L84-L93

**Comment by nisdas** [comment]
> One more thing to fix is to remove the call to depositCache.AllDepositContainers during log processing. Because the cached deposits will no longer contain all data from the original deposits, log processing should handle processing and saving deposits internally instead of fetching cached deposits every eth1DataSavingInterval.

What do you mean by this ? Log processing isn't fetching the deposits here, it is just saving it to the db. It already does handle processing and saving deposits to the cache..

**Comment by rkapka** [comment]
After digging a bit deeper into which parts of deposits are used, it turns out that only proofs can be safely removed. The current solution is to remove deposit `d` from cached pending deposits and remove `d.Proof` from cached deposits when block that includes `d` gets finalized.

*Note:*
Make sure that removing a deposit from the pending deposits slice does not remove the same deposit from the deposits slice in case both point to the same object in memory.

Associated Discord discussion starts here: https://discordapp.com/channels/476244492043812875/730447046930071672/743764601446858753

**Comment by rkapka** [comment]
Small update - I plan to handle this issue next week.
