### ISSUE TITLE
Refactor Blockchain, Casper and Types Packages to Simplify Beacon Chain Architecture 

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#470]
Currently `core.go` holds beacon chain database, state snapshots, a lock and many more methods. Some of those methods can be converted to be stateless and some methods really belong in types (which is what the state package is called) and casper package. There's some overlap and we could find a better way to organize `block chain`, `casper` and `types` packages better.

This issue addresses how to clearly defining each package as well as refactoring them.

**Comment by rawfalafel** [comment]
With the recent refactor (https://github.com/prysmaticlabs/prysm/commit/f312c013fcc677c1fdc29a36ff03e93a1367db0d), a lot of `core.go` code got moved over to `block.go`, `active_state.go`, and `crystallized_state.go`. I'm going to start working on migrating over to Bolt, which will move the rest of the database logic into its own package as well. 

I think the distinction between `types` and `casper` is a little blurry, since they both contain logic that's related to Casper somewhat. `types` imports `casper` but not the other way around, and `casper` deals strictly with protobuf messages when handling state. 

Would be nice to better organize these packages. Otherwise, we could just close this?

**Comment by terenc3t** [comment]
Sounds good closing this. Thanks for refactoring `core.go` and types package.
