### ISSUE TITLE
Please Use Go Module

### ISSUE THREAD

**Issue by dappstore123** [prysmaticlabs/prysm#480]
Please use Go module instead of bazel.

**Comment by rauljordan** [comment]
Can you elaborate on this @dappstore123? Can you explain what you mean by this? Is this an issue advocating for replacing our entire build system?

**Comment by dappstore123** [comment]
yes. https://golang.org/doc/go1.11#modules

**Comment by dappstore123** [comment]
maybe bazel is better。

**Comment by prestonvanloon** [comment]
Is there a path where we can use go module and bazel? We have been maintaining the project such that you could use native go tools, without bazel, if you so desired.

We like bazel for the incremental builds (I think go does incremental builds natively now), the ability for remote execution and caching of builds (this will be helpful for CI as the project grows), the upcoming support for uploading build actions remotely (see tensorflow's PR invocation results [example](https://source.cloud.google.com/results/invocations/728eeceb-0e79-4654-8c85-fac64d9bf147/targets)).

Bazel and go modules are beta tooling and have their trade offs. I'm open to discussing alternatives, but we would need a strong argument to remove bazel in favor of something else.

**Comment by prestonvanloon** [comment]
I would like to hear more about how we can leverage modules in this project.

For the time being, we are supporting building via native go tooling and building via bazel. Occasionally, we have pain in our continuous integration linter since it fetches dependencies at HEAD and there are often breaking changes.

If we can easily peg specific versions of modules to make building by go easier then I would happily support that effort.
