### ISSUE TITLE
One validator key with an incorrect password causes all to fail

### ISSUE THREAD

**Issue by superphiz** [prysmaticlabs/prysm#4955]
When launching the validator client with three validator keys, one had a password that was not provided correctly and the validator failed with:

`ERROR main: could not get private key: could not decrypt key with given passphrase`

The ideal behavior is that the validator would continue to validate for keys with the correct passphrase while aggressively reporting the warning for the key(s) with incorrect passwords. One bad key should not stop the whole show.

**Comment by prestonvanloon** [comment]
@mcdee Do you have any input/ideas about this issue?

**Comment by mcdee** [comment]
We can't easily change the keystore format to have multiple passwords at this point, as it would break others' installations.  Probably best to do as @superphiz suggests and warn for any keys we cannot decode, but continue rather than exit.  I'll code something up to this effect.

The long-term solution is to move to the `wallet` keystore, which supports multiple passphrases.  I'll think of the best way to move ahead with a migration plan.
