### ISSUE TITLE
Deposit_Data fields defined as slice or array differs in ssz type

### ISSUE THREAD

**Issue by imnisen** [prysmaticlabs/prysm#4957]
I have a question about the **ssz** `hash_tree_root` implementation used in function `DepositInput `:
https://github.com/prysmaticlabs/prysm/blob/76aad0f44414b53d647a7e40bf65acb88f52d415/shared/keystore/deposit_input.go#L25

When calculating the `hash_tree_root` of the `DepositMessage`,  as the [spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#depositmessage)  says the field `DepositMessage .pubkey` is type `BLSPubkey ` which is `Bytes48` which is a alias of `Vector[byte, N]` as [ssz spec](https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md#aliases). The same as the field `DepositMessage . withdrawal_credentials `.

However, as the function DepositInput use `ethpb.Deposit_Data` [(ethereumapis),](https://github.com/prysmaticlabs/ethereumapis) the struct is as below:

```
type Deposit_Data struct {
	PublicKey             []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WithdrawalCredentials []byte   `protobuf:"bytes,2,opt,name=withdrawal_credentials,json=withdrawalCredentials,proto3" json:"withdrawal_credentials,omitempty"`
	Amount                uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	......
}
```

It uses golang type slice `[]byte`, which would be processed as `List[byte, N]` in [go-ssz](https://github.com/prysmaticlabs/go-ssz) `hash_tree_root` if I didn't misunderstand it. The result differs.

So should the struct (generated by protobuf) defined as an array not slice? something like below. Or may I make some mistakes?

```
type Deposit_Data struct {
	PublicKey             [48]byte   
	WithdrawalCredentials [32]byte   
	Amount                uint64   
	......
}
```

**Comment by nisdas** [comment]
Hey @imnisen , we use `ssz` tags on our proto objects. Since protobufs do not allow for fixed sized arrays, we have to add tags to specify what length the arrays are going to be. We do not specify them in the [ethereum-apis](https://github.com/prysmaticlabs/ethereumapis) repo, but instead add them in the patch over here:
https://github.com/prysmaticlabs/prysm/blob/master/third_party/com_github_prysmaticlabs_ethereumapis-tags.patch

 https://github.com/prysmaticlabs/prysm/tree/master/third_party#ethereum-apis-patch

The above readme gives a good description of how it works

**Comment by imnisen** [comment]
That's great! I didn't see it before.
