### ISSUE TITLE
keymanageropts path not being expanded

### ISSUE THREAD

**Issue by tzapu** [prysmaticlabs/prysm#4998]
if you use 
`--keymanageropts='{"path":"~/prysm-keys/","passphrase":"changeme"}' `
you might expect prysm to use the homefolder for ~, instead it will create a `'~'` folder in the current path and use that

**Comment by mcdee** [comment]
The single quotation mark tells the shell not to expand anything inside it.

There are a couple of ways around this.  One would be to have a file instead of supplying the data directly on the command line, for example: `--keymanageropts=~/opts.json` and then have a file at `~/opt.json` that contained:

```
{
  "path": "/the/actual/path",
  "passphrase": "changeme"
}
```

This has the benefit of not making your passphrase visible to anyone with access to the server.

Alternatively you can avoid using single quotes altogether and escape the double quotes that are present in the JSON, for example ` --keymanageropts="{\"path\":\"${HOME}/prysm-keys/\",\"passphrase\":\"changeme\"}" `

(Note use of $HOME rather than ~; ~ is not expanded anywhere inside quotes)

**Comment by tzapu** [comment]
cool, the first option looks interesting. 
wanted to flag me because i wasted a lot of time trying to find out why multiple validator keys were not loaded because they were in the "wrong" folder and I can see how someone else would run into this as well

**Comment by mcdee** [comment]
We're in the process of transition from old-style to new-style functionality so there are some rough edges.  I'll add in a check when seeing a path with shell-type characters (~ or $) in it to warn of this condition.

**Comment by tzapu** [comment]
sounds great. feel free to close this or i can if you want

**Comment by mcdee** [comment]
Let's hold it open to remind me to do the work :smile:
