### ISSUE TITLE
Allow gRPC Client Load Balancing

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#5132]
Currently, we do not allow a single validator to connect to multiple beacon node backends in a round robin fashion. Ideally, we should be able to do `--beacon-rpc-provider=BEACON_NODE_IP_1,BEACON_NODE_IP_2` from the validator client, but we have to do some gRPC setup for this to work. Thanks to @mcdee, this link on stackoverflow https://stackoverflow.com/questions/50293480/dial-multiple-ip-addresses-with-golang-grpc-client can help us achieve this. This is a great first issue for anyone wishing to contribute.

**Comment by xrow** [comment]
Great idea....

What would happen if you have an lb in between? Will that work?

```
validator 1  ---->|                                                    |-----> beacon 1
                           | ------>    Loadbalancer  ----->   |
validator 2  ---->|                                                    | ----> beacon 2
```

**Comment by mcdee** [comment]
Depends how the load balancer would work.  Safest way would be to prefer one node over another, _e.g._:

  - on validator startup shuffle the list of nodes
  - connect to first beacon node
  - if first node fails at any point, connect to second beacon node

This could easily be extended to multiple load balancers.

There's also a question as to if the load balancer should be a separate process or baked in to the validator.  I'd be inclined to do the latter for now, unless there's a really good reason to do otherwise.  Running additional processes can be a pain, and for the initial case this is looking to solve probably overkill.

This would change your diagram to look something like:

```
validator 1  ----> Load balancer (internal) | -----> | beacon 1
                                              \    /
                                               \  /
                                                X
                                               / \
                                              /   \
validator 2  ----> Load balancer (internal) | -----> | beacon 2
```

**Comment by xrow** [comment]
@mcdee Thanks for your feedback. As a side note to clearify. I have much experience with cloud native so I will simulate this case for it. An internal loadbalancer in Cloud Native would be a so called Service. A service is a dns based named endpoint like "beacon". Behind beacon there are multiple beacon nodes. I would estimate the current implementation is therefore sufficent if a validator 1 can talk to "beacon 1" on the first request and to beacon 2 on the second. Is this the case?

**Comment by mcdee** [comment]
@xrow It is entirely possible for beacon nodes to have different states.  What I'm unsure about is if it matters for our normal validator operations when we're carrying out multiple RPC requests that could go to different beacon nodes; perhaps Raul has some thoughts on that piece.

A primary/secondary configuration would certainly be safer than a round-robin configuration, but I may be worrying unnecessarily about the impact of the latter.

**Comment by prestonvanloon** [comment]
This issue is about client side load balancing. See the examples here: https://github.com/grpc/grpc-go/tree/master/examples/features/load_balancing

I think this requires a bit of careful thinking. Some RPC calls will want to load balance as a failover and others will want to load balance as a "broadcast".

Here's an example workflow:
- GetAssignments (LB=Round robin or pick first, retry failed requests to other backends)
- GetBlock (LB=round robin or pick first, retry failed requests to other backends)
- ProposeBlock(LB=Send to all backends, any success = success)
- GetAttestation(LB=round robin or pick first, retry failed requests to other backends)
- ProposeAttestation(LB=Send to all backends, any success = success)

The main idea here is that we have some sort of failover redundancy from the client. Imagine you run your own node, but IF it ever went down then you fail over to some free or managed service. This would be "pick first" where your node is prioritized. Additionally, some requests, like publishing new data, would go to all backends to increase propagation of the new objects.

**Comment by mcdee** [comment]
Dynamic attestation subnets somewhat push us away from being able to carry out simple round robin, as we could send an attestation to a beacon node that isn't subscribed to the relevant subnet.

**Comment by xrow** [comment]
I don't know, if this is possible from what I read or even allowed. I in general favor a model for clients to not have any LB logic. Therefore can the logik of ProposeBlock and ProposeAttestation handled by one backend talking to other backends after the inital request? Some kind of replication....

**Comment by prestonvanloon** [comment]
Good point about the round robin strategy and attestation subnets. You have this assumption that the beacon node backends are either always connected to appropriate subnets or can quickly discover subnets for adequate and rapid propagation of unaggregated attestations. 

With that said, one can imagine that some RPC calls have different strategies such as

| RPC | Strategies |
|--------|-------------|
| GetAttestationData | Pick first or round robin, failover | 
| ProposeAttestation | Broadcast * Depends on subnet subscriptions * | 
| GetBlock | Pick first or round robin, failover |
| SubmitBlock | Broadcast |
| SubmitAggregateAndProof | Broadcast * Depends on subnet subscriptions * |
| ProposeExit | Broadcast |
| DomainData | Pick first or round robin, failover |
| GetDuties | Pick first or round robin, failover * Influences subnet subsctiptions * |
| ValidatorIndex | Pick first or round robin, failover | 

The two RPCs that are most affected by subnet subscriptions are ProposeAttestation where the beacon node should to be connected to the specific subnet already to propagate the attestation faster and SubmitAggregateAndProof which aggregates as many of the unaggregated attestations as possible then broadcasts to a topic that everyone is subscribed to. There is no penalty or reward for inefficiently aggregated attestations from SubmitAggregateAndProof, except for the resilience of the network. Additionally, the beacon node becomes aware of which subnets to subscribe to based on GetDuties and GetAttestationData calls. These calls should stick with the "primary" beacon node, but are safe for failover.

**Comment by mcdee** [comment]
This is starting to morph in to a more complicated beast.  Similar to the initial suggestion and diagram posted by @xrow I'm starting to wonder if an "Ethereum 2 proxy/router" would be a thing.  It would basically be the piece that manages peer connections and data movement.  The beacon node could stay as it is for full functionality without the router, but this would give additional features such as the varied strategies of load balancing we're discussing here.

If standalone it would also work for all clients, which would be interesting.

**Comment by prestonvanloon** [comment]
There isn't much work to do here for server side load balancing. 

I'd still like to consider a client side load balancer, at least for failover.

**Comment by xrow** [comment]
I guess is if you have implemented retry you do not need a client side load balancer. One highly available endpoint should do the trick. You can combine dns, ip, location failover via the lb. But I rather stay clam now since I don`t understand the protocol yet. Sorry :-) 

I am currently working on a helm chart. With that I can demo server side lb.

**Comment by xrow** [comment]
Are there limits for how many validators can connect to one beacon node? I saw somewhere the figure  64 or doesn`t it matter?

**Comment by xrow** [comment]
Hi,

I would like to see a different meaning of `--beacon-rpc-provider=BEACON_NODE_IP_1,BEACON_NODE_IP_2` . My idead that should be just used for failover and not for loadbalancing. Maybe we can implement failover frist and then lb later. The great benefit of this is we can then live without a global loadbalancer in our setups and have only local ones per DC.

`--beacon-rpc-provider=BEACON_NODE_IP_1,BEACON_NODE_IP_2 --beacon-rpc-ha-type=failover`
Try BEACON_NODE_IP_1 3 times if dead discard it. Then try BEACON_NODE_IP_2 3 times if dead discard it and try next again. 

`--beacon-rpc-provider=BEACON_NODE_IP_1,BEACON_NODE_IP_2 --beacon-rpc-ha-type=loadbalance`
Round Robin without stickyness.

**Comment by xrow** [comment]
Hi,

I wanted to report I am running now this model and didn`t notice any issues.
```
validator 1  ---->                \           / ----->  [ beacon 1 ]
                                              \      /                                    
                                                \  /
                                  Load balancer (internal)
                                                / \
                                              /     \
validator 2  ---->                /          \  ----->  [ beacon 2 ]
```

**Comment by xrow** [comment]
This is the overall picture. Please send in corrections.

![Overview](https://user-images.githubusercontent.com/295491/80988842-5c86c080-8e34-11ea-853b-d310e2a96d62.png)

**Comment by prestonvanloon** [comment]
@xrow that is server side load balancing. L4 / L7 load balancing would work well for power users, but having a client side load balancer where the validator could failover to a beacon chain node running in an entirely different data center or region would be ideal for many use cases.

**Comment by xrow** [comment]
I was thinking about moving the validators to a different datacenter if a datacenter has downtime. Though it needs some kind of election of a leader if validators pop up somewhere else. Usually the network is down in those failure events so there is no route to connect to a failover beacon node. Client side loadbalacing is still a great choise, but can`t garantee 100% uptime of the validator. So if you think about failures validators and beacon nodes may fail.

**Comment by nobsu** [comment]
At present, has server-side load balancing been implemented?

**Comment by prestonvanloon** [comment]
There are solutions for proxy load balancers, yes. These solutions aren't
specific to Prysm as a generic gRPC proxy load balancer would work.

https://grpc.io/blog/grpc-load-balancing/
