### ISSUE TITLE
Release --protect-proposer and --protect-attester for Testnet Restart

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5267]
Currently we do not require our validators to have a db to protect them against accidentally slashing themselves. This should be the default for running our validators in the next testnet restart. Although this might affect our k8s deployments as now all our validator clients will need to have a db. @prestonvanloon would this be possible to implement for our next testnet restart ?

**Comment by terencechain** [comment]
Imo this is optional. Most of the user slashings we have seen in cluster are due to multiple node instances (ie, different zones) using the same set of the keys. In this case, having a localize DB will not help.

I think this is a nice to have, but just not sure how much protection it realistically applies...

**Comment by prestonvanloon** [comment]
We haven't tested this in runtime at all.

We can invert the flag so that the default is ON, but I don't think we should remove this flag entirely yet.

**Comment by 0xKiwi** [comment]
I agree with Preston here, it hasn't be thoroughly tested on runtime in the
cluster. We should enable it on the cluster for a little bit at least
before releasing.

Validators haven't committed any slashable offense right? The network has
been stable, less likely for validators to accidentally slash period.

**Comment by prestonvanloon** [comment]
Starting this change now.
