### ISSUE TITLE
Validators with PENDING status included in Previous epoch voting summary

### ISSUE THREAD

**Issue by janexlolz** [prysmaticlabs/prysm#5485]
![image](https://user-images.githubusercontent.com/45725266/79630569-1c002500-815b-11ea-94be-1a529c7b262a.png)

**Comment by terencechain** [comment]
thanks for reporting this! this is indeed an issue and should be a relatively easy fix. Marked as a `Good First Issue`

**Comment by ShawkiS** [comment]
Hey guys, I didn't get the idea of the issue, Is there more details?

**Comment by prestonvanloon** [comment]
@ShawkiS The problem here is that the user has 5 validator keys. Only 2 of these are active. The feature request is to only log "previous epoch voting summary" for activated validators as this log is not helpful for pending ones. A pending validator had no duties in the last epoch and there is really nothing to report on their performance.

Generally, we want to only print this message when this condition is true
```go
	if validator.Status == ethpb.ValidatorStatus_ACTIVE || validator.Status == ethpb.ValidatorStatus_EXITING {
```
See #5397 for an example how duties logs were cleaned up, maybe you could do a similar clean up for this request. 

Assigning to @ShawkiS, let me know if don't want to work on this and I'll unassign. Thanks!

**Comment by ShawkiS** [comment]
That's great, thank you I'll start working on it :+1:

**Comment by ShawkiS** [comment]
I have to edit validator_metrics.go where we do the condition I check if the validator status is ethpb.ValidatorStatus_ACTIVE or ethpb.ValidatorStatus_EXITING?
