### ISSUE TITLE
Initial sync exited too early

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5490]
See below screen shot. Initial syncing exited at 4582/4632 slot and started requesting parent block....

<img width="1276" alt="Screen Shot 2020-04-18 at 8 29 05 AM" src="https://user-images.githubusercontent.com/21316537/79642140-bc048100-8150-11ea-8a50-e2587c85e9ab.png">

**Comment by prestonvanloon** [comment]
Is there any additional information here? Sounds like your client synced with the peer majority and exited.

**Comment by farazdagi** [comment]
This is more of a reporting issue:
- when reporting progress we have `current slot / known slots since genesis`, but of course init sync never reaches that known slots (it eventually will switch to normal sync to wrap up those near final slots)
- still, init-sync comes as close as possible to the known slots: when init-sync reaches the highest requested slot, before exiting it re-requests whether a better finalized slot is available (from majority of peers), and if so - continues (this is especially important when we have huge chain and init-sync takes some time)
- our idea was (I assume): show the max slot, so that end-user is aware of the goal towards which we are syncing

So, two options here:
- Make sure that the second number is not slots since genesis **during the init-sync**, but the highest slot towards which init-sync is progressing. In that case, when that highest slot will be reached, and node switches to normal sync, all of a sudden, we will have a new highest slot (as previously reported one was the highest init-sync slot).
- Leave as it is, assuming that `cur slot / max known slot` is what users expect to see (and that they do not care whether part of that road was covered by init-sync/phase1, init-sync/phase2, or normal sync). Here, we also need to make sure that "block processed" message is the same for all the phases on sync (init and normal), so that end user sees phases as essentially a single process (syncing to head).

Thoughts?

**Comment by terencechain** [comment]
I'm ok with leaving it as it is without spending too much time on this.  Do you think we are ok to close this? @farazdagi
