### ISSUE TITLE
Initial Sync Out of Memory Panic

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#5540]
# 🐞 Bug Report

### Description

A user reported an out of memory exception during initial sync, not very deep into the testnet (around block 400)

## 🔥 Error

[https://pastebin.com/5fb9ZxcY](https://pastebin.com/5fb9ZxcY)

**Comment by farazdagi** [comment]
The issue is most probably not new, related issue: https://github.com/prysmaticlabs/prysm/issues/5390

**Comment by rauljordan** [comment]
This was due to new-state-mgmt, which is being resolved by @terencechain

**Comment by terencechain** [comment]
This is not a `new-state-mgmt` memory issue, the new state mgmt issue only persists post initial sync when a node is receiving valid aggregated/unaggregated attestations because of the state copies for verifying those attestations.


This is a diff issue as we can see from the log the node runs out of memory in slot 400
```
[2020-04-20 15:29:17]  INFO initial-sync: Processing block 449/19046 - estimated time remaining 35m49s blocksPerSecond=8.7 peers=3
fatal error: runtime: out of memory
 
runtime stack:
runtime.throw(0x1738bcf, 0x16)
    GOROOT/src/runtime/panic.go:1112 +0x72
runtime.sysMap(0xc034000000, 0x4000000, 0x27af3f8)
    GOROOT/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x27967a0, 0x400000, 0x263d020, 0x0)
    GOROOT/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x27967a0, 0x1, 0x0)
    GOROOT/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x27967a0, 0x1, 0x1200, 0x27af408, 0x7ff8889a9ec8)
    GOROOT/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
    GOROOT/src/runtime/mheap.go:871 +0x64
runtime.systemstack(0x0)
    GOROOT/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
    GOROOT/src/runtime/proc.go:1041
```

With that said, I'm not aware of any reporting of this today
