### ISSUE TITLE
Operations on validator db to manage validators

### ISSUE THREAD

**Issue by Phistr90** [prysmaticlabs/prysm#5638]
# 🚀 Feature Request 

### Description

For validator management purposes it would be nice to have a possibility to move certain validators from one instance to another. Currently all the validators information on a client are all stored in a single validator db. This makes it difficult to scale and balance load as it is not possible to move validators to another client

### Describe the solution you'd like

Helpful operations might be: merge(db_1,db_2) , split([Val1,..,Val_k],[Val_k+1,..,Val_n], db_2)

These two operations would allow to move some validators to a another validator client.

With merge and split another operation on db_1 could be import([Val_1,..,Val_k], db_2) to import validators Val_1,..,Val_k from db_2 into db_1.

### Describe alternatives you've considered

An alternative might be to have a db for each validator.

**Comment by thor314** [comment]
I might be able to help with this, though I'm not a very experienced developer. May I discuss this with someone on Discord?

**Comment by alonmuroch** [comment]
@Phistr90 as I understand most of the db usage for the validator is slashing protection isn't it?

**Comment by rkapka** [comment]
Hi!

I would like to work on this issue. I have already discussed this on Discord and got a green light.

**Comment by prestonvanloon** [comment]
@rkapka can you link to the discord conversation here please?

**Comment by rkapka** [comment]
Certainly.

https://discordapp.com/channels/476244492043812875/667763844365680650/708239399048970301

**Comment by rkapka** [comment]
I have some doubts about how the merging part should be implemented.

1. This issue's description makes a distinction between `merge(db_1, db_2)` and `import([Val_1,..,Val_k], db_2)`. To me this means that merging should create a completely new database. If this is the case, then should the following function be used?
https://github.com/prysmaticlabs/prysm/blob/42278359d99dc30492c37013dbd9161dbc84873c/validator/db/db.go#L68
If it should, then some keys have to be passed to the function and, as far as I understand, merging should not deal with keys.
2. If I create a new file `validator/db/manage.go`, can I use it directly from `validator/main.go` or should I introduce another layer of abstraction?
3. Should my `Merge` function take a `ctx context.Context` parameter similarly to functions in `attestation_history.go` and `proposal_history.go`? I have a feeling that using context here doesn't make much sense because attestations/proposals are conceptually different that off-chain commands like merging validator data. If I do need to use it, then how can I get hold of it in `main.go` to pass it along to my function?
I have to admit I don't fully understand this context thing. I think of it right now as some kind of an abstraction over request/response flows like HTTP.
4. What is the purpose of `validator/db/iface/interface.go`? If I have a `Merge` function in `manage.go`, should it be included in the interface?

**Comment by rkapka** [comment]
After some discussion with @rauljordan on Discord (the relevant stuff starts here: https://discordapp.com/channels/476244492043812875/667763844365680650/709444111224143914) the current way to implement this feature is over several PRs:

- [ ] Merge keys
- [ ] Merge databases
- [ ] Split/Import (may be broken into several PRs in the future)

**My idea on how to merge keys**
The users provides a comma-separated list of source directories and a target directory. For each source directory the user is asked to provide a password to decrypt keys. The user is also asked to provide a new password to encrypt the merged keys. The keys are then copied into a single file/directory (not sure if one file can hold several keys) and encrypted, or the other way around.

**Comment by wgknowles** [comment]
Conversation about merging db's starts here: https://discord.com/channels/476244492043812875/476588476393848832/704163563635212330

**Comment by rkapka** [comment]
I gave this some thought and here is my current standpoint on merging:

> The way the validator client runtime works is through the function NewValidatorClient (...) You should be able to call such logic in either that function or perhaps in the inside of NewKVStore, depending on your proposed design.

I don't think spinning up a new client is necessary to do a merge. Let's do the merge in the context of the already running client initialized by the `validator` command. The merge will append data from source databases into the current client's database. This will partially cover the requested import functionality (resulting in data from all validators being imported into the current client's database, equivalent to manually specifying all validators when importing).
If the user wants to merge `db1` and `db2` into a new, empty database, then they  invoke `validator accounts create` followed by `validator accounts merge`.

The command will require a comma-separated list of source directories.

On a side note, I am not sure what would happen if I tried to run another client whilst one is already running. If they shared the same CLI context, things might get strange 😀 

> that function should take in a context, which should be the context of the ValidatorService struct https://sourcegraph.com/github.com/prysmaticlabs/prysm/-/blob/validator/client/service.go#L36

If my above reasoning makes sense, then I should use the context from the existing client. But how to access it from within the subcommand's code in `main.go`? The client is created inside the `startNode` function. I can modify the function to return the client, but that won't help me because it's only assigned in `app.Action = startNode` and not invoked anywhere.

**Comment by rauljordan** [comment]
Done by #5986

**Comment by rkapka** [comment]
@rauljordan This feature is not done yet. Please see my comment with the list of operations to implement.

**Comment by rkapka** [comment]
I have been thinking what other operations might be useful apart from merging ans splitting and here are my proposals:

1. Export - the user specifies a source directory, a target directory and a list of public keys k_1..k_n whose data should be exported from the source directory's database. A new database containing the exported data is created in the target directory.
_Question: Should the exported data be removed from the source database? Maybe add a boolean flag to control this?_
2. Import - the user specifies a source directory and a target directory. All data from the source database is copied to the target database.
3. Move - the user specifies a source directory, a target directory and a list of public keys k_1..k_n whose data should be moved from the source directory's database to the target directory's database. _Question: Should the moved data be removed from the source database? Maybe add a boolean flag to control this?_
4. Split (k_1..k_n) - splitting currently creates one database for each source database's key. Add a flag that allows to specify keys whose data should be split from the rest. As a result, two new databases are created: one with data for keys k_1..k_n and one with data for the rest of the keys. The source database stays untouched (this behaviour will be consistent with the "regular" split).
_Question: Splitting one database into N databases will be tedious in case N is not a very small number. The keys could be passed in a more complicated manner, e.g. [k_1..k_n],[k_x..k_y]. As an example, passing `[k1,k2],[k3,k4,k5]` would create three databases:_
    - _data for k1 and k2_
    - _data for k3, k4 and k5_
    - _data for the rest of keys (if there are any left)_

Remark:
Export could be achieved using Move by creating a new database if the target directory does not contain one. Import could be achieved using Move by moving all keys over to the target database if no keys have been provided. I am wondering if it is better to have multiple operations, each doing their own thing, or a single powerful operation. Or maybe both?

**Comment by rauljordan** [comment]
Hi @rkapka move seems to be the most requested operation from folks. People wonder how they can perhaps move their keys safely with instructions to other machines or folders. We might not need move if we can implement import and export nicely. Those can perhaps output a zip file, which can be imported by another validator client.

**Comment by rauljordan** [comment]
Closing in favor of #6220
