### ISSUE TITLE
AppendValidator recreates full validator set index map on every usage

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#5779]
To add more validators to the state, we use [AppendValidator](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/state/setters.go#L672) which recreates the `valIndexMap` for the entire validator set each time it is used.

This is incredibly expensive during genesis state creation, and gets more expensive as more validators are added.

**Comment by nisdas** [comment]
#5780 will help with this, by reducing the amount of time on map copies. However due to us having no way of tracking the map, our ability to reduce the amount map copies here is limited. 

If we do need to improve it further we can track references to the map between all the states which share it like our other fields in the state. However that would be more involved to do and would clash with how we track fields in the state as this would be a non-state value. That would be the optimal solution here to reduce the amount of map copies.
