### ISSUE TITLE
eth.v1alpha1.BeaconNodeValidator.GetBlock reconstructs depositTrie on request (500ms)

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5801]
https://github.com/prysmaticlabs/prysm/blob/87e0fe59283989cbe63796d72613a882a4f9504b/beacon-chain/rpc/validator/proposer.go#L293-L317

This method appears to be taking about 500ms of the critical path of block production. There are a few things we should fix here:

- Determining the DepositTrie is only necessary when there are pending deposits for inclusion. We're currently calculating it for every block, whether or not there are deposits ready to include.
- The DepositTrie should be cached, if possible. Computing this on demand is expensive.
- We're computing the DepositTrie up to the latest eth1 block, but it should only compute up to the canonical eth1 block since only deposits up to the canonical eth1 block can be included anyway.

**Comment by 0xKiwi** [comment]
How should caching this be handled? Maybe expanding upon `DepositFetcher` to be more aware of the deposit trie?

**Comment by prestonvanloon** [comment]
With the second and third point together, we wouldn't need to recompute the deposit trie again since the canonical eth1 block changes about once per voting period (1024 slots), so this would be an ideal candidate for caching the latest 2 or 3 values.

**Comment by rauljordan** [comment]
@rkapka

**Comment by rkapka** [comment]
Please assign me to this issue.

**Comment by nisdas** [comment]
This was discussed offline in discord with @rkapka , summarizing it over here.

When deciding on how to cache the trie and where to cache it, there are two possibilities on which height to cache it. Namely the height up till our last finalized checkpoint or the latest 'valid' eth1data.

1) Finalized Checkpoint:
By caching the trie upto our eth1data in our finalized checkpoint. We have a stable base on which to build, and continue adding any additional deposits. We know for the most part, this will not change (excluding a major protocol fault). From this we can continue building the trie upto which ever eth1block that we wish to.

2) Latest Eth1Data:
By Caching upto the latest eth1data, we continually make sure that our trie is the most upto the latest `valid` ethdata from the node's view. Ex: `Current_head` - `follow_distance` . This is usually accurate as the follow_distance gives us a margin of safety for any eth1 re-orgs. We expect each new 'valid' `eth1_block` we receive to be the direct child of our previous 'head eth1_block' , using this we can assume any new deposit coming in can be added directly into the trie. 

However there can be certain situations where this approach will not work and we will have to rebuild the trie. Our node has a different eth1 view compared to other nodes in the network. When proposing a block we build the deposit trie upto a selected `eth1_data` tuple. This can either be the `eth1_data` in the state or the latest `eth1_data` from our node's point of view. Optimistically building the trie and caching it according to the latter case is fine, however for the former there could be a discrepancy if all the other node's in the network vote in for a completely different eth1data from the point of view of our node. We would then have to rebuild the whole trie, as the cached deposit trie would be referencing some other `eth1_data` tuple.

Namely the advantages of 1) are that the situation above cannot happen except in the case of a major protocol fault. It also allows us to handle any possible situations in which other nodes differ from our view of the eth1 chain. We can always add in the appropriate deposits onwards from the latest finalized checkpoint.

The advantages of 2) is that it does optimistic caching of deposits, so in the average case what our node sees of the eth1 chain lines up with what other nodes see too, caching the deposit trie this way would be fine. This will lead to us requiring less deposits to be inserted into trie, and also less time spent rebuilding branches in the deposit trie.

**Comment by rkapka** [comment]
Implementation proposal outline:

- Add a new field `finalizedDepositsTrie *SparseMerkleTrie` to `DepositCache`.
- Add a new function `(dc *DepositCache) InsertFinalizedDepositsTrie()` to `deposits_cache.go` and invoke it from `onBlock()` in `process_block.go` whenever `postState.FinalizedCheckpointEpoch() > s.finalizedCheckpt.Epoch`. Most likely pass the `postState.state.Eth1DepositIndex` as a parameter, rebuild the tree in `InsertFinalizedDepositsTrie()` and store it in the `finalizedDepositsTrie` field.
- Retrieve the cached trie within `deposits()` an build the final deposit trie by inserting pending deposits into the cached trie.
- Profit :-)

Q1: Can we be sure that `PendingDepositsFetcher.PendingContainers()` will return the correct deposits, i.e. it won't return any cached "finalized" deposits?
Q2: I am not sure if `finalized` is the best name because I don't think there is technically such a thing as a finalized deposit. Maybe some other name would be better?

**Comment by terencechain** [comment]
Any specific reason why `postState.FinalizedCheckpointEpoch() > s.finalizedCheckpt.Epoch` is the trigger? Will justified work? or certain intervals?

**Comment by rkapka** [comment]
Please see the above comment from @nisdas. I think that the best solution would be a mixture of the two possibilities that he presented, although I am not exactly sure how this could work. Maybe we could also update the cached trie from inside `deposits()` in certain scenarios, but then it could get overwritten on epoch finalization.

**Comment by rkapka** [comment]
Hey @prestonvanloon, point 2 from your list has been implemented in #6391 and point 3 was not an issue - it turned out that the trie was computed up to the correct block. It was the variable names that were poor and didn't describe what was actually happening. The names have been corrected.

Are you able to run some sort of benchmark in order to verify whether trie caching resolved the issue?

**Comment by rauljordan** [comment]
@prestonvanloon following up on this thread

**Comment by prestonvanloon** [comment]
My main point here is that `latestEth1DataHeight` only changes every 4 hours, so we don't need to reconstruct this trie again until another Eth1Data is inserted into the beacon state. I believe the caching helped fetching the deposits, but this methods still calls the expensive `GenerateTrieFromItems`.

**Comment by rkapka** [comment]
This part of the code executes whenever there are any finalized deposits. The cached trie is used instead of a call to `GenerateTrieFromItems`. If there are no new non-finalized deposits, then the cached trie is returned directly, otherwise the non-finalized deposits are inserted into the cached trie.

`GenerateTrieFromItems` is called only in the special case when the deposits cache is empty.
https://github.com/prysmaticlabs/prysm/blob/2c11fcb2427625779ba02cd9ea2591f187f2c4b4/beacon-chain/rpc/validator/proposer.go#L362-L378

**Comment by prestonvanloon** [comment]
![Screenshot from 2020-08-06 00-50-47](https://user-images.githubusercontent.com/7246818/89505738-f1c08a80-d77e-11ea-8587-48e3c7bd4490.png)

Something is still slow about GetBlock, if it's not due to reconstruction of the depositTrie.

@rkapka That renaming makes sense to me

**Comment by prestonvanloon** [comment]
![Screenshot from 2020-08-06 17-37-45](https://user-images.githubusercontent.com/7246818/89596283-a1dbd500-d80b-11ea-8d49-a205e401ae92.png)

Looks like this might be resolved. Lets check again after more data can be collected from #6903 in prod.

**Comment by prestonvanloon** [comment]
I need a bit more time on this. Since our validators were slashed over the weekend, I don't have recent data on block proposals. 

We just sent another round of deposits which should be included in the next 3 to 4 days. At that time, we should have some span data to understand how long block proposals are taking. Thanks

**Comment by prestonvanloon** [comment]
![Screenshot from 2020-08-27 11-59-19](https://user-images.githubusercontent.com/7246818/91483633-d9fb9400-e85c-11ea-9580-4ca08324fd91.png)

This looks like it is resolved. Thanks!
