### ISSUE TITLE
Assert that only non-processed blocks are sent in init-sync queue

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#5857]
### Description

Follow-up issue of https://github.com/prysmaticlabs/prysm/pull/5856

### Describe the solution you'd like

Make sure that only not yet processed blocks are sent for processing (this de-dup can take place in round robin or queue - queue seems to be more appropriate place).

### Describe alternatives you've considered

We have considering implementing this in block processing routine - but it introduces unnecessary complexities.

**Comment by terencechain** [comment]
It's more so `duplicated` block. For `new-state-mgmt`, it still processes the block since it syncs from check point to check point and only preserve state in DB on check point. Currently this can happen:
Sync queue: [blkA, blkB, blkC, blkC, blkD] -> process_block
What we want:
Sync queue: [blkA, blkB, blkC, blkD] -> process_block
