### ISSUE TITLE
Starting the slasher crushes the RPC link between the BC and the validator

### ISSUE THREAD

**Issue by Arxis75** [prysmaticlabs/prysm#5878]
Running BC+Validator on a VPS server. As soon as I start the slasher, the validator RPC connection with the BC gets crushed and the validator stops attesting.

Typical Validator error message: "level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator"

Killing the slasher brings immediately my validator to properly attest.

Ubuntu 20 VPS with 32Go mem, 8xCPU and NVMe disk. The server is NTP Synced.
BC: v1.0.0-alpha.8
Validator: v1.0.0-alpha.8
Slasher: v1.0.0-alpha.8

**Comment by allsilent** [comment]
Same Issue. 51 Validators and a BC on a Raspberry Pi 4 (4Gb RAM) with Ubuntu 20.04 and an SSD.

Validators vote appropriately, and the Pi doesn't struggle, mem usage and load are both nominal.

As soon as the slasher starts up, it appears to crowd the RPC connection so that Validators can't submit attestations. Nothing but repeating "level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator" as soon as the slasher is running.

Running the slasher with historical detection disabled. Starting the slasher will "take down" all the validators as described. Stopping the slasher will instantly resume normal validator operation. It does not appear to be a CPU/Memory issue, as load and memory usage do increase but not to OOM-threatening levels. 

I have Grafana and can restart my slasher to catch the exact metrics before the validators "die off" if it helps, but that won't highlight any potential RPC issues to my knowledge.

BC/Validator/Slasher: alpha.8

**Comment by allsilent** [comment]
Worth noting that this differs from previous slasher issues with regards to p2p as well. In this case, peers stay high (35+ in my case) and the BC and Validator client continue to operate, but seem unable to communicate.

**Comment by stefa2k** [comment]
I'm running beacon/validator/slasher on a 4gb RAM machine and I run into issues with `level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator` only when the machine also runs out of memory.

**Comment by stefa2k** [comment]
I can replicate it now with docker.

I observed now 2 things:
1. If I set --max-goroutines to 10,000 the effect takes longer to be visible
2. If I restart the slasher and it already HAS a database it doesn't stress the beacon that much.

**Comment by prestonvanloon** [comment]
@stefa2k `--max-goroutines` only affects a status check. It should not affect any performance of the application. 

@shayzluf @0xKiwi @rauljordan can you guys please take a look at the issue?

**Comment by 0xKiwi** [comment]
This is an issue I've been experiencing with my slasher. For real-time detection there are no issues but for historical detection where the slasher is just demanding so much computation from the beacon node constantly, I start seeing that context deadline issue.

I think the slasher might be too fast now lol, it finishes an epochs worth of attestation processing quickly and immediately asks for more. Beacon node might be getting genuinely overwhelmed.

What is there that can be done to handle this?

**Comment by 0xKiwi** [comment]
After thorough investigation of what could be going wrong, I believe this issue has been solved by a few changes:
* #5958 no longer starts historical detection (the choking process) on startup, it isn't as important as realtime detection anyways. Better to make realtime detection easier to run.
* #5971 changes `StreamIndexedAttestation` to use the target root to grab that state, which means there is nearly 0 state regen for realtime detection. This should be clearing most of the problem.
* #5999 changes `StreamIndexedAttestation` to process the attestations it has received 2/3rds into a slot. This prevents the heavy computation from interfering with role assignments to validators.

This issue still exists for historical detection, but I consider this non-essential for users wishing to run a slasher.
