### ISSUE TITLE
Validator metrics are partially available without the flag --enable-account-metrics

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#5883]
# 💎 Issue

### Background

One of the user didn't understand why he didn't have access to all the metrics from the validator process since he has access to http://localhost:8081/metrics. He didn't use the `--enable-account-metrics`

### Description

In the previous version, if you don't add `--enable-account-metrics` to the validator command, then you don't have access at all to http://localhost:8081/metrics
Now it seems like some of the metrics are still getting through without it, and it is misleading some users. I'm also not sure this is a wanted behavior at all.

I would personally expect either you enable everything or either you don't want anything.

**Comment by prestonvanloon** [comment]
To give a bit of background on this, having validator account metrics on by default causes high data carnality which can inflate retention sizes in tsdb. This is only a concern to users running many validators. So the current behavior is working as intended but it does have some user confusion. 

I'm going to mark this as a feature request to invert the flag functionality. Power users can opt-out of validator account metrics rather than having most users opt-in.

**Comment by prestonvanloon** [comment]
I've added #5904 to make account metrics enabled by default. This should resolve the issue. Thanks!
