### ISSUE TITLE
Implement Deterministic Sqrt Helper Function

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#593]
The Eth2.0 implementation teams have decided it's best off to define a deterministic sqrt helper function rather than the built in implementation for various languages. This is to reduce errors across implementations on consensus critical calculations which will be used by the rewards scheme. 

To resolve this issue, we should implement the helper function mentioned [here](https://github.com/ethereum/eth2.0-specs/pull/13) and use it in our casper package.

**Comment by djrtwo** [comment]
note, this PR https://github.com/ethereum/eth2.0-specs/pull/14 has a more robust implementation of `int_sqrt`

**Comment by nisdas** [comment]
@djrtwo I had one more issue with the calculation of rewards/penalties in the spec, specifically this line:
`(total_participated_v_deposits - total_v_deposits) // total_v_deposits`, this calculation would always have to be done using floating point arithmetic otherwise the result would always be zero. Any way we can change this to be more deterministic, otherwise subtle bugs will be introduced across different clients which would be difficult to detect

**Comment by nisdas** [comment]
@djrtwo Thanks for clarifying that ! Unfortunately it looks like I unnecessarily introduced floating point arithmetic into our reward calculations, will get that changed now.
