### ISSUE TITLE
 Previous epoch aggregated voting summary displays incorrect stats (sometimes)

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6257]
# 🐞 Bug Report

### Description

` Previous epoch aggregated voting summary...`  displays incorrect stats sometimes. In my setup, it has been reported 0% inclusions the last few epochs but such reporting didn't align with beacon block explorers.

```
 Previous epoch aggregated voting summary attestationInclusionPercentage=0% correctlyVotedHeadPercentage=0% correctlyVotedSourcePercentage=0% correctlyVotedTargetPercentage=0% epoch=158
```

### Has this worked before in a previous version?

Yes. In Topaz

## 🔬 Minimal Reproduction

Run validators

**Comment by handelaar2** [comment]
I noticed the same thing during startup of the Onyx chain. It seems to me that `GetValidatorPerformance` is returning the wrong results sometimes. I below screenprint of the validator log, one can see that the new_balance of the previous epoch does not match  the old_balance of the current epoch. In the previous epoch, one can also see all the "false"-votes and the big inclusion distance (although nothing was wrong). As of the below "current epoch", things were all normal again.
![2020-06-15_08-12-38](https://user-images.githubusercontent.com/28559038/84624412-9cd06880-aee1-11ea-8f0b-e66cb577ed37.png)

**Comment by ppunktw** [comment]
Had this problem since network start. My validators (100 total) have been running smoothly but the reporting was mostly messed up. As you can see on the graph, sometimes it reported the voting correctly but the balance was still off (was never below 3.2k ETH). Only in a few cases, everything was reported correctly. 
I tried restarting the validator & beacon and also did a --clear-db on the validator. Didn't help. But approx. 6h ago, it seems to have fixed itself (without me doing anything).

![image](https://user-images.githubusercontent.com/25792899/84636260-add6a500-aef4-11ea-80e6-a50315d15701.png)

(Running my own geth node btw.)
