### ISSUE TITLE
Running validator client in HA

### ISSUE THREAD

**Issue by ayushpateria** [prysmaticlabs/prysm#6491]
Hi, is it possible to run the validator client in a highly available setup probably using Kubernetes? With the current implementation in boltDb is there any way around it?

Also, is it possible to run multiple validator clients connected to the same boltDb instance? I think it's important for multiple clients to have the same instance for slashing protection to work correctly.

**Comment by prestonvanloon** [comment]
Hey @ayushpateria, great question! 

This is a tricky problem to solve. With high availablity, you want things like automated failover and data replication. 
However, this type of setup could easily lead to a slashable condition if not configured correctly. 

The validator client will secure a lock around a boltDB storage file, so only one process can use it at a time.
In kubernetes, you could consider a statefulset or a deployment with a persistent volume claim. At least here if your validator process gets evicted then you can have it rescheduled safely, assuming the persistent volume can only be mounted to one pod at a time. 

The validator client is rather lightweight and not very prone to crashes or restarts. The bulk of the hard work is done in the beacon chain node. You can run multiple beacon chain nodes in your k8s cluster and connect the validator to a service that load balances requests. It is recommended that your load balancer uses a "sticky" balancing scheme as a beacon node will need to subscribe to a certain p2p subnet in order to effectively propagate your attestations. A round robin style load balancer could see delays in attestation inclusion since the beacon node may be unaware of the incoming request. 

I hope that helps answer your question. Thanks!

**Comment by terencechain** [comment]
Closing this as there's no more follow up
