### ISSUE TITLE
Huge memory amount used by validator

### ISSUE THREAD

**Issue by Belkaar** [prysmaticlabs/prysm#6804]
# 🐞 Bug Report

### Description

Validator uses lots of ram, about 2-3GB for me.
Memory usage is gradually reduced if system memory gets full as used by other processes (eth1 node for example).
After a while memory usage is normal.

### Has this worked before in a previous version?

Don't know. Did not use accounts-v2 until now.

## 🔬 Minimal Reproduction

System memory: 4gb
* Start beacon
* Start a validator with accounts-v2 "direct" wallet with 14 keys in it.
* Observe memory usage
* Start eth1 node
* Observer memory usage

## 🔥 Error

No error messages

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian 10
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.0.0-alpha.17
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by Belkaar** [comment]
![image](https://user-images.githubusercontent.com/2395990/89018431-2b773880-d31c-11ea-92d9-d4f6da0a1e31.png)

![image](https://user-images.githubusercontent.com/2395990/89018537-53ff3280-d31c-11ea-85d0-eb09084ecf63.png)

![image](https://user-images.githubusercontent.com/2395990/89018642-75601e80-d31c-11ea-9ce7-b292f483464b.png)

![image](https://user-images.githubusercontent.com/2395990/89018715-8d37a280-d31c-11ea-843c-e07ad1981cba.png)

**Comment by prestonvanloon** [comment]
We've done some investigation and this is due to the scrypt parameters in [EIP-2335](https://eips.ethereum.org/EIPS/eip-2335).
We looked at the [scrypt code](https://github.com/golang/crypto/blob/123391ffb6de907695e1066dc40c1ff09322aeb6/scrypt/scrypt.go#L205) and how it allocates memory. In this investigation we found that each key allocates about 67Mb (`262144*32*8 + 64*8 = 67109376 bytes`). 

Give the quarks of Golang's garbage collector, you will notice that this allocated memory is not cleaned up right away, but it is cleaned shortly after. 

We have considered the following two options:
- Modify the scrypt library to reuse the same allocated slices with sync.Pool or similar, then decrypt the keystores sequentially.
- Store Prysm keys in a slightly modified version of EIP-2335 where `n` keys live in the same json file and only need to be decrypted once instead of doing `n` rounds of decryption.

The first option seems dangerous, but feasible. Modifying crypto libraries is not something we take lightly so we avoid it whenever possible. So the second options seems like a reasonable approach. It doesn't compromise on user security as keys are still encrypted at rest.

**Comment by rauljordan** [comment]
We are proceeding with option 2 with an automigrate feature for users that have already imported their accounts

**Comment by Belkaar** [comment]
Without looking at the code, cant garbage collection be forced after every key import?

**Comment by prestonvanloon** [comment]
It could be done but this would make the start up process even slower with multiple keystore decryptions. Some users are reporting there keys taking several minutes to open when they have 64 to 100 keys!

Option 2 seems like the best approach since it would only use 268Mb and reduce start up time significantly when running more than one keystore.
