### ISSUE TITLE
Out of memory on beaconchain process

### ISSUE THREAD

**Issue by SickLead** [prysmaticlabs/prysm#6942]
# 🐞 Bug Report

### Description

Maybe this is already reported, but I would like to share a problem of the beacon node – 2 core/4gb ram/80 gb SSD. I am waiting for validation of my validator and when I start the beaconnode, sometimes I run out of memory on my droplet and I need to restart the beacon node manually.

I don’t really know if it has anything to do with the fact that the validator is still not validated on the network, however I have another validator running (and validated) with the same configuration setup and I don’t encounter this problem.

The beacon node stopped working an the linux kernel killed the process due to a too high memory usage.

## 🔬 Minimal Reproduction

Run command for a not yet validated validator:

**Geth**
geth --goerli --datadir="$HOME/Goerli" --rpc

**beaconchain**
~/prysm/prysm.sh beacon-chain --p2p-host-ip=$(curl -s v4.ident.me) --http-web3provider=$HOME/Goerli/geth.ipc --log-file $HOME/beaconChain.log

## 🔥 Error

<pre><code>
Aug  8 05:26:59 Medalla2 kernel: [123442.812675] Out of memory: Kill process 9016 (beacon-chain-v1) score 595 or sacrifice child
Aug  8 05:26:59 Medalla2 kernel: [123442.815059] Killed process 9016 (beacon-chain-v1) total-vm:5108624kB, anon-rss:2472716kB, file-rss:0kB, shmem-rss:0kB
Aug  8 05:26:59 Medalla2 kernel: [123442.980812] oom_reaper: reaped process 9016 (beacon-chain-v1), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
</code></pre>

(->see logs at the end)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
digitalocean droplet 2 core/4 GB Memory / 80 GB Disk / FRA1 - Ubuntu 18.04.3 (LTS) x64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm version is v1.0.0-alpha.19.
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
https://beaconcha.in/validator/25817

[beaconChain.log](https://github.com/prysmaticlabs/prysm/files/5047257/beaconChain.log)
[kern.log](https://github.com/prysmaticlabs/prysm/files/5047258/kern.log)

**Comment by Chriton** [comment]
The "Out of memory" memory happened to me also but I was running on a Raspberry Pi 3 model B v1.2 with 1gb ram on Ubuntu 64bit. Now I am running the beacon chain and validator on a raspberry pi4 with 8gb ram and works fine.

**Comment by rauljordan** [comment]
Hi @Chriton 4Gb was not enough during the incident the testnet suffered this past weekend. We have some big improvements in the pipeline and usage should be a lot lower now. You should be ok at the moment with 4Gb.

**Comment by nisdas** [comment]
@Kyrrui Could you provide more details here ? 
Ex: 
- What are the specs on your droplet
- The flags you are running the node with
- Any other processes that are running alongside the beacon node.
- Logs before your node has an OOM

As far as we are aware, there have been no reports on excessive memory consumption with v1.3.10 so any information will be helpful.

**Comment by prestonvanloon** [comment]
![Screenshot from 2021-06-16 09-24-20](https://user-images.githubusercontent.com/7246818/122237129-b1449980-ce84-11eb-942b-bc0010a86727.png)

@nisdas here's a data point on digital ocean. It sounds like they are using 4GB ram droplet.

**Comment by Kyrrui** [comment]
@nisdas Hello! So I upgraded my node to the $40 a month version temporarily so I don't have anything saved but can describe the setup I had and the behavior.
The node is running a validator client with a graffiti tag, the ETH2 beacon chain was running with just the '--http-web3provider' flag connected to an infura endpoint.
The log was just normal output then 'killed'. I looked into the system logs and found that the system ran out of memory. To be safe I shut down the validator and started up the beacon chain alone, but it still ran out of memory. @prestonvanloon is correct on the droplet I am running. I do want to say this has been a continuous issue, but only happened every couple of weeks before hand, since the latest release, the beacon chain hasn't been able to sync without running into the OOM issue. For reference here is my validator https://beaconcha.in/validator/9946982d09a2f6106251e12a5c2009b478cdb1c19201e16df7976a5ff578c68e7fc80a2d610201b8281e5e84ee4e087b
