### ISSUE TITLE
eth/v1alpha1/validators/participation returns wrong data

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#7116]
> This API only gives you the voted ether precisely at the end of epoch `N` whereas it can still grow through` N+1`
> So at the end of epoch 4805, you can run that endpoint for 4805 and get the balances then at the end of 4806, you can look at "previous" and get the final balance result
> 
> Is the participation rate the head, target, or source pariticpation?
> "target" is what matters for justification so it might be the relevant number to show
> If there was a bunch of forking, you could imagine a source participation that was much higher than target and thus depending n what was displayed could be confusing

http://localhost:3500/eth/v1alpha1/validators/participation?epoch=4805
```
epoch    "4805"
finalized    true
participation    
globalParticipationRate    0.36303958
votedEther    "373192000000000"
eligibleEther    "1027965000000000"
```
Lighthouse reports 78%
https://lighthouse-book.sigmaprime.io/http/consensus.html#consensusglobal_votes

quoting @djrtwo here as he found the issue, thanks :)

**Comment by terencechain** [comment]
This looks like a limitation of the participation end point, it only counts target balances from the canonical chain, and not the forked chains.

**Comment by fabdarice** [comment]
Can help with that if you need @terencechain.

**Comment by terencechain** [comment]
Thanks @Buttaa for opening this. Fixed with #7117 

```
curl -X GET "http://localhost:3051/eth/v1alpha1/validators/participation?epoch=4805" -H "accept: application/json"
{"epoch":"4805","finalized":true,"participation":{"globalParticipationRate":0.75779724,"votedEther":"778989000000000","eligibleEther":"1027965000000000"}}%
```

**Comment by djrtwo** [comment]
wait, should it include orphaned blocks? I would expect the endpoint to be for on-chain participation

The issue here is that at the end of epoch `N`, participation was pretty low _because_ there were a number of orphaned blocks. But by the end of epoch `N+1`, participation was reasonable high because the attestations got filled in in slightly "late" blocks. Because the finality and reward calculations for epoch `N` happen at epoch `N+1`, it seems reasonable to count activity in epoch `N+1` as well

A side note: what does `globalParticipationRate` mean here? The granularity of seeing head vs target vs source has been really useful when following lighthouse metrics as each "participation rate" has it's own meaning about network performance. For example for beaconcha.in's "epoch" view, it seems natural to use on-chain correct "target" participation because that is the cleanest signal of finality health per-epoch



[lighthouse endpoint if interested to check it out](https://lighthouse-book.sigmaprime.io/http/consensus.html#consensusglobal_votes)

**Comment by terencechain** [comment]
> wait, should it include orphaned blocks? I would expect the endpoint to be for on-chain participation

If the orphaned blocks have attestations for the correct target root, they still should be counted no?

> But by the end of epoch `N+1`

Makes sense. It currently uses the start of `N+1`. End of `N+1` is more correct in this context

> `globalParticipationRate`
That's just the target rate. We certainly should update this API to include source and head as well

**Comment by terencechain** [comment]
Changed from start of `N+1` to end of `N+1`. Getting the exact percentages as lighthouse 🙌 

```
 curl -X GET "http://localhost:3051/eth/v1alpha1/validators/participation?epoch=4805" -H "accept: application/json"
{"epoch":"4805","finalized":true,"participation":{"globalParticipationRate":0.779474,"votedEther":"801272000000000","eligibleEther":"1027965000000000"}}%
```

**Comment by djrtwo** [comment]
> If the orphaned blocks have attestations for the correct target root, they still should be counted no?

well! it depends on what you're counting.

If you are counting just all the attestations that exist (maybe for understanding the fork choice), then you should include all branches and attestations not in branches. For the purposes of understanding on-chain health, would no include orphans

**Comment by terencechain** [comment]
> would no include orphans

Yeah I see it now. Querying to the end of `N+1` would have fixed this
