### ISSUE TITLE
Password for recovered HD wallet rejected 

### ISSUE THREAD

**Issue by divdev2000** [prysmaticlabs/prysm#7294]
# 🐞 Bug Report

### Description

Password validation fails attempting to list a recovered HD wallet created with validator wallet-v2 recover 

### Has this worked before in a previous version?

Yes, I can access the same wallet using the expected password and v1.0.0-alpha.25
USE_PRYSM_VERSION=v1.0.0-alpha.25 ./prysm.sh validator accounts-v2 list

It appears to be only the version used to access the wallet that matters.  Wallets created with alpha.25 or alpha.26 are both accessible using alpha.25

## 🔬 Minimal Reproduction

1) ./prysm validator wallet-v2 recover 
create recovered wallet with 
seed phrase: box mandate notable tool base rail special north live target question mixture focus cluster era double horn toddler real hurt point vanish dress stick
password: 4bMW*"5Lrd

2) ./prysm.sh validator accounts-v2 list
enter password: 4bMW*"5Lrd

## 🔥 Error

<pre><code>

FATAL accounts-v2: Could not list accounts: wrong wallet password entered

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu Desktop 20.04 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.26
  </code>
</pre>

**Comment by dv8silencer** [comment]
When you recover, if you put 0 accounts when it asks
`Enter how many accounts you would like to recover (default: 0):`
and then afterwards recover the number of accounts you have using
`accounts-v2 create --num-accounts 10`  (10 as an example)
Does it work?

If so likely https://github.com/prysmaticlabs/prysm/pull/7295 by @rauljordan will resolve the issue.  https://github.com/prysmaticlabs/prysm/pull/7295/files#diff-e86d56bd5c8d484f84795c34b49584df line ~165 fixes it so that when recover is asked to create accounts as well, it will respect the input password.

**Comment by divdev2000** [comment]
Yes, I tried what you suggest and it does work if I start the recovery with 0 accounts and then create them afterwards my password is accepted.
