### ISSUE TITLE
Beacon Node Still Returns Out of Order Blocks From Range Requests

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#7464]
# 🐞 Bug Report

### Description

Currently Lighthouse Peers score Prysm Nodes down due to the fact that prysm nodes occasionally 
send back out of order blocks. 

### Has this worked before in a previous version?

Supposed to. 

## 🔬 Minimal Reproduction

Run a Prysm Node in medalla, and after a while lighthouse nodes start banning them.

## 🔥 Error

```
DEBUG sync: Peer has sent a goodbye message Reason=unknown goodbye value of 251 Received 
```
Consistent goodbyes received from lighthouse nodes.

## 🌍  Your Environment

**Operating System:**

Ubuntu

**What version of Prysm are you running? (Which release)**

https://github.com/prysmaticlabs/prysm/commit/390a589afb6a38925b2d6da25a3df3d4f84a9bf7

**Anything else relevant (validator index / public key)?**

**Comment by farazdagi** [comment]
Nishant, are you absolutely sure that disconnects are due to out of order blocks? It seems we already deduplicate and sort the list of returned blocks:
https://github.com/prysmaticlabs/prysm/blob/48fcb08ebc2bb0ae4686618f94b5bd5178c96477/beacon-chain/sync/rpc_beacon_blocks_by_range.go#L147-L156

I've checked the implementation -- everything seems to be intact. So, I wonder whether there might be sth else resulting in descoring/banning?

**Comment by AgeManning** [comment]
The responses that are sent are definitely one of the major sources that is causing issues between Lighthouse and Prysm. 

The specific error we are seeing is that at least one block in the chain segment returned did not have its parent root set to the root of the prior block sent.

It may be the case the blocks are ordered and de-duplicated. After a quick skim of this code, perhaps its the case that some blocks are filtered for not being canonical. In which case you may send us a series of blocks that do not form a chain?

We are expecting a response from a blocks by range response to be a series of blocks linked together via their parent root hash in order. I think perhaps the hash linking in some cases could be broken here?

**Comment by nisdas** [comment]
@AgeManning You are right in that is most likely the cause. @farazdagi and I discussed this offline and came to the same conclusion, the remaining issue we would probably have to figure out is why we do receive non canonical blocks from our database. In our interop efforts to debug this, the epochs requested were already finalized so technically all blocks returned should be canonical. Something we will have to continue digging at.

**Comment by mcdee** [comment]
Tangentially related, but regarding 'non-canonical' blocks: it would be useful if nodes kept around orphaned blocks, for data analysis purposes.  Unsure if you consider a block that was generated by the correct proposer but not part of the chain non-canonical, but if you do please either don't discard it during pruning, or have an option for same.

(Unless the issue is that _receiving_ non-canonical blocks is causing problems, but I would suggest that is an issue with the receiver.)
