### ISSUE TITLE
validator sugests a parameter that's missing from it's help

### ISSUE THREAD

**Issue by emile2738** [prysmaticlabs/prysm#7552]
![image](https://user-images.githubusercontent.com/69115862/96269774-a77a3780-0f7f-11eb-8fa6-2d87dd43dccc.png)

suggests using --ssl-no-revoke 

while it's not documented in help

root@prysm00:/home/emile/dist# ./validator-v1.0.0-alpha.28-linux-amd64 --help | grep ssl
root@prysm00:/home/emile/dist# ./beacon-chain-v1.0.0-alpha.28-linux-amd64 --help | grep ssl
root@prysm00:/home/emile/dist# ./beacon-chain-v1.0.0-alpha.28-linux-amd64 --help | grep -i ssl
root@prysm00:/home/emile/dist# ./validator-v1.0.0-alpha.28-linux-amd64 --help | grep -i ssl

**Comment by raphpa** [comment]
This is not implemented correctly in the launch scripts.

`--ssl-no-revoke` is a parameter of curl.

Some anti virus solutions inject their own SSL certificate into a secure http connection to be able to monitor malicious downloads. Curl fails, if not called with `--ssl-no-revoke` at this because it cannot fetch the revoke list for that self signed certificate and has to be called with that parameter.

You probably can argue about having it set by default.

**Comment by rauljordan** [comment]
This is tricky. I'd prefer we not add --ssl-no-revoke to our script, but instead recommend stakers to download the script directly from our releases page if they are having issues
