### ISSUE TITLE
Web UI and Wallet Password not accepted

### ISSUE THREAD

**Issue by ChuckNorrison** [prysmaticlabs/prysm#7586]
# 🐞 Bug Report

### Description

iam testing the current beta and the new web ui. After starting my validator with `--web `and `--web-host `parameter, i can get into the login page of the new web ui.  After entered the wallet password created with account-v2 in previous version with spadina testnet, the password gets rejected with `Needs at least 1 uppercase letter, 1 number, and 1 special char`

### Has this worked before in a previous version?

No Web UI in previous versions

## 🔬 Minimal Reproduction

Password with numbers, chars and some special chars i.e. `%(['&>-`

## 🔥 Error

<pre><code>
`Needs at least 1 uppercase letter, 1 number, and 1 special char`
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 Server
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
beta.0rc
  </code>
</pre>

**Comment by rauljordan** [comment]
@ChuckNorrison please see our release notes for beta.0.rc https://github.com/prysmaticlabs/prysm/releases/tag/v1.0.0-beta.0.rc, specifically the known issues section:

> --web UI is broken. We decided to move forward with the beta.0.rc release with the UI in a partially unusable state to faciliate Medalla recovery fixes

Apologies for the inconvenience, it will be fixed in the next release

**Comment by littleskunk** [comment]
My feedback on this topic:

Prysm is currently not stable. In the announcements, we have been told to watch out for deprecated parameter because in the next release the deprecated parameter will be removed. It was a surprise to me that also other parameters have been removed without any deprecate warning. I am using docker and leave the updates to watchtower. My problem is not so much that the web frontend was not finished. I fully understand that part. Next time please be more careful playing around with any parameters. This was not the only parameter that was removed without a warning!

**Comment by ChuckNorrison** [comment]
early stage can be confusing to users, especially if breaking changes are happening. Iam fine with it, even the docs do not coverage all dependencies. For zinken and spadina testnet it would have be useful to get this Information in release notes, to not get users try to debug for hours ;)
