### ISSUE TITLE
API returns block data for orphaned slots in finalized epochs

### ISSUE THREAD

**Issue by peterbitfly** [prysmaticlabs/prysm#8064]
# 🐞 Bug Report

### Description

It would be good if it is possible to disable returning orphaned blocks via the prysm API. Currently for example the following request on mainnet will return a block that has been orphaned:

<pre><code>
curl localhost:3500/eth/v1alpha1/beacon/blocks?slot=43331
</code></pre>

An API consumer gets no indication that the block is not canonical and will need to traverse the blockchain by parent root hashes in order to identify that block as an orphan. A good solution would be to include a `canonical` flag alongside the block data. 

## 🌍  Your Environment

**Operating System:**
<pre><code>Ubuntu </code></pre>

**What version of Prysm are you running? (Which release)**
<pre><code>v1.0.3</code></pre>

**Comment by nisdas** [comment]
@terencechain , is it desirable to return non canonical blocks here, or should we be more strict on the kind of blocks returned by the endpoint ?

**Comment by pinglamb** [comment]
@nisdas I checked the https://github.com/ethereum/eth2.0-APIs and it doesn't mention orphaned blocks should be excluded. 

Although `block` response itself doesn't have the `canonical` flag, the `block header` response has. So instead of traversing the blockchain by parent root, another call to fetch the `block header` is enough to check if the block is `canonical`.

https://github.com/ethereum/eth2.0-APIs/blob/master/apis/beacon/blocks/block.yaml#L21
https://github.com/ethereum/eth2.0-APIs/blob/master/apis/beacon/blocks/header.yaml#L25

Is it okay for `prysm` to not follow the spec and respond extra data? like having `canonical` flag in `block` response as well.

**Comment by peterbitfly** [comment]
@pinglamb this issue refers to the current Prysm API and not to the harmonized eth2.0 API.
