### ISSUE TITLE
Prysm API returns slashing rewards and  block rewards in different epochs

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#8154]
# 🐞 Bug Report

### Description

The issue seems to be that even though slashings are included in a block, that the Prysm api returns the rewards for slashings in the next epoch and for block rewards after two. 
Which is why the rewards in 3690 are +0.06256 ETH (slashing) and 3691 +0.00214 ETH (block proposal). It should however be +0,06470 ETH in Epoch 3690 (block+slashing)

https://mainnet.beaconcha.in/validator/15703#balanceChart

![image](https://user-images.githubusercontent.com/26490734/102612306-c8ead180-4130-11eb-86c9-76ec8d7e4686.png)

**Comment by Buttaa** [comment]
Attestations seem to +1 epoch

**Comment by potuz** [comment]
After reviewing it carefully and given the information provided in 

https://discord.com/channels/476244492043812875/603588441741066241/796008807088128031

I believe nothing can be done by prysm here. The API call beaconcha.in is using requests the validator balances at the beginning of each epoch. The relevant rewards are awarded as follows (notation is from the spec) and the epoch/slot number are as in the example in the description: the validator proposed a block in epoch 3691 including a slashing

1. The whistleblower reward, which is currently awarded to the block proposer, is awarded immediately on this callpath
`slash_validator` <--- `process_proposer/attester_slashing` <---- `process_operations` <---- `process_block` 

So this reward is given immediately and will be picked by the balance call in epoch 3692. 

2. The proposer rewards are computed inside `get_inclusion_delay_deltas` on epoch processing. The way epoch processing works is by taking all attestations from the previous epoch. This previous epoch is explicit in this line:
```
matching_source_attestations = get_matching_source_attestations(state, get_previous_epoch(state))
```

After that for each such attestation we give a reward to the validator with index `attestation.proposer_index`. This means, that in the epoch transition 3691 --> 3692, the attestations from epoch 3690 were picked up and to each block proposer from that epoch some rewards were given. Our validator that proposed in 3691 will not see these rewards until the transition 3692 --> 3693. 

I believe at the time of the picture taken, beaconcha.in was subtracting 2 epochs from each call, making it consistent to here. There is nothing that can be done on prysm side regarding this API call. However, it seems to me that beaconcha.in could assume the slashing reward is in epoch N-1 since this is immediately awarded. And block proposals and attestations are in epoch N-2.  Having said so, there is this screenshot posted in Discord

https://discord.com/channels/694822223575384095/768206298734788618/790992876968345610

That gives a counterexample to that, I am not sure how can that happen.

**Comment by potuz** [comment]
Thinking about this issue, I think what beaconcha.in should be doing is the following: 

1. When a validator attests in epoch N and no block with a slashing was proposed in epoch N+1, assign the balance change reported at epoch N+2 to epoch N. 
2. In the other situation:  When a  validator attests in epoch N and proposes with a slashing in epoch N+1 then compute the slashing rewards, these have very simple formulas
```
    whistleblower_reward = Gwei(validator.effective_balance // WHISTLEBLOWER_REWARD_QUOTIENT)
    proposer_reward = Gwei(whistleblower_reward // PROPOSER_REWARD_QUOTIENT)
```
The constants are in the specs and the effective balances are kept by beaconcha.in anyway. 

After computing this reward then report the balance change of epoch N+2 minus this reward in epoch N. Report the balance change of epoch N+3 plus this reward in epoch N+1

Care must be taken in the case a validator proposes in two consecutive epochs.

**Comment by pinglamb** [comment]
@rkapka To conclude, I think it is not a `prysm` bug. The `proposer rewards` from `attestations inclusion` and `slashing` reflected in different epochs is an expected behaviour according to `eth2-specs`. `slashing reward` will be reflected in same epoch as block proposal and `attestations inclusion reward` will be reflected in next epoch. So I think this issue can be closed.

How to have `Balance Change`/`Reward` reported in beaconcha.in is a separate topic.
