### ISSUE TITLE
Use `eth_chainID` instead of `net_version`

### ISSUE THREAD

**Issue by MariusVanDerWijden** [prysmaticlabs/prysm#8170]
# 💎 Issue
Prysm currently uses `net_version` to query for the chain id. While this works in most cases, it might make it possible to connect to an ETC node by mistake as discussed here: https://eips.ethereum.org/EIPS/eip-695

Generally the `eth_chainID` should always be preferred to `net_version`
Additionally geth currently has a bug which impacts `net_version` and makes it impossible to run prysm with the current master, see: https://github.com/ethereum/go-ethereum/issues/22034

While we are going to restore the `net_version` RPC call, it would be better to move to `eth_chainId`.

**Comment by nisdas** [comment]
Hey @MariusVanDerWijden ,

Thanks for reporting this, we are required by the specs to query for both chain id and network id.
https://github.com/ethereum/eth2.0-specs/blob/dev/configs/mainnet/phase0.yaml#L55

Which is why the error comes up on our end, I can open up an issue in the official specs repo to open this up for discussion.

**Comment by nisdas** [comment]
Alright @MariusVanDerWijden opened an issue here:
https://github.com/ethereum/eth2.0-specs/issues/2163

**Comment by james-prysm** [comment]
Assuming this issue has been resolved with closing of https://github.com/ethereum/consensus-specs/issues/2163
