### ISSUE TITLE
deposit merkle branch of deposit root did not verify for root  error

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#8298]
# 🐞 Bug Report

### Description
Reported by @adamluc

Hitting this error when trying to propose a block: 

```
ERROR validator: Failed to request block from beacon node blockSlot=357477 error=rpc error: code = Internal desc = Could not compute state root: could not calculate state root at slot 357475: could not process block: could not process block operation: could not process block validator deposits: could not process deposit from 0xa44a77caaa1f: could not verify deposit from 0xa44a77caaa1f: deposit merkle branch of deposit root did not verify for root: 0x4f5b3879d8ac0297c73af79a9e509840ae32704b1b5f4c792e1451d5eb4dce48 pubKey= 
```
Here is the block that actually included the deposit 
https://beaconcha.in/block/357478

And here is the valid deposit that failed to be processed 

https://beaconcha.in/validator/82570#deposits

**Anything else relevant (validator index / public key)?**
https://discord.com/channels/476244492043812875/667761857209040916/801296166788136972

**Comment by prestonvanloon** [comment]
Investigating this. Immediate thoughts/ideas are:
- User was missing some deposits, due to a missing or unstable eth1 connection
- eth1 experienced a reorg with one or more deposits forked out
- The deposit was actually invalid, but was not filtered out for block inclusion

**Comment by adamluc** [comment]
Thank you. If there is any other information that could be helpful, please let me know. 

Thanks
Adam

**Comment by potuz** [comment]
> Investigating this. Immediate thoughts/ideas are:
> 
> * User was missing some deposits, due to a missing or unstable eth1 connection
> * eth1 experienced a reorg with one or more deposits forked out
> * The deposit was actually invalid, but was not filtered out for block inclusion

The deposit seems valid and it got included in the linked block. The user is using infura which wasn't capped. It's a tough bug to diagnose,

**Comment by prestonvanloon** [comment]
@adamluc Could you confirm the Prysm version and commit you were running at the time?

@potuz Yes, very curious... Could be a bls caching issue too. I am assuming Adam was able to process the block with the deposit (and verify the deposit signature) eventually since they haven't reported their chain completely stalled.

**Comment by adamluc** [comment]
I am running v 1.05, on OS X 10.15.7. Upgraded a few days after 1.05 came out. Not sure where to get the commit ID, I am using the Mac OS X terminal and .prysmsh for the execution method.

**Comment by prestonvanloon** [comment]
@adamluc You were probably running v1.0.5, in that case. Thanks!

**Comment by rauljordan** [comment]
Has this been observed since then @potuz ?

**Comment by potuz** [comment]
I haven't heard of any report except @adamluc's it must be some freak edge case

**Comment by terencechain** [comment]
Background on why we raised this to critical, we believed that this issue has appeared today starting epoch 32320.
For 18 epochs, many missing blocks on mainnet, but chain was still finalizing. We believe it's an issue with how Prysm believes deposits should exist in blocks is causing state root failures as Prysm has a different idea of block poststate from other clients

The issue seems to go back after a certain amount of time if no deposits are seen, but will manifest itself every eth1 voting period (around every 4 hours), which is giving  us breathing room to identify and resolve the problem

**Comment by mrabino1** [comment]
FWIW. Checkout https://beaconcha.in/epoch/32317 

something happened also where prysm missed it attestation on mass. Not sure if it is related.

**Comment by prestonvanloon** [comment]
The affected epochs were 32302 through 32320. Any epoch between those is
related to this incident.

>
