### ISSUE TITLE
Beacon Node Logs Stop Appearing With Web UI

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8430]
# 🐞 Bug Report

### Description

It has been reported by users that when running with the web-ui beacon node logs eventually stop appearing, and after a few hours the validator attached stops functioning leading to missed attestations.

### Has this worked before in a previous version?

Before v1.2.0

## 🔬 Minimal Reproduction

Run the beacon node and validator with the web ui to trigger the error. This eventually leads to 
the beacon node logs going missing and the validator eventually having missing attestations.

## 🔥 Error

This has been brought up offline and in #8314 .

**What version of Prysm are you running? (Which release)**

v1.2

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
After digging through the code, I am not convinced web is the problem. It seems here that the node somehow freezes, which is unrelated to web. I originally thought this could be due to the logs stream, however, we migrated away from websockets and known issues with nodes freezing due to a bad websocket issue. Now, logs are simply sent as streams via gRPC, they can no longer freeze a beacon node. There have been reports of nodes stopping and seeming like they are crashed in Discord and in those cases, the parties involved were not using --web. I think the issue is unrelated. It it possible they also hit the known deadlock bugs before 1.2

**Comment by rauljordan** [comment]
Commented on the other issue to ask the stakers to let us know if they are still seeing the issue after disabling the web interface

**Comment by LouisDiesser** [comment]
I disabled WebUI now and until now everything works fine, but after I had the issue for the second time in v1.1.0 it also worked fine for some weeks with WebUI enabled. I'll let you know, if it happens again.

**Comment by alancwoo** [comment]
As a note, I had the same problem in v1.1.0 on Linux with the web ui enabled, the logs would just be halted/frozen. I've updated to 1.2.1 and will report if this happens again.

**Comment by nazar-kuzo** [comment]
@rauljordan Hey, strangily, but on v 1.2.0 I had no issues for a week or so, updated to v 1.2.2 and after 2-3 hours beacon node stopped sync with no error, and logs appear in the WebUI. I`m using ubuntu VM.

**Comment by ahadda5** [comment]
my 2 cents as a user of the node
1- ran ./prysm.sh validator --web
2.  Missed attestation were noticed after about 8hrs (basically slept, woke up and ) things were not functioning. 

I removed the --web and restarted.  All went back to normal . 

System:  ubuntu 20.04
NEtwork:   georli
