### ISSUE TITLE
Safety Start: monitor at least 1 epoch for duplication before starting attestation

### ISSUE THREAD

**Issue by quangld** [prysmaticlabs/prysm#8513]
# 🚀 Feature Request

### Description
Validator will monitor the network at least 1 epoch before starting attestation, just to make sure there is no duplicate validator running somewhere

### Describe the solution you'd like
add a safety start switch:
` --delay-attestation=x `
where x is the number of epochs that the validator will monitor the network for its duplication attestation before starting to attest

### Reason
I'm afraid that I accidentally start my validator when it's actually already running on the same machine or somewhere else.
For example: I migrate my server to another one and forget to stop the validator (or it's set to start automatically on reboot)

**Comment by nisdas** [comment]
@potuz Taking the conversation here:

I wrote a short design doc on something with similar goals a while back:
https://hackmd.io/@prysmaticlabs/B16P-Bbgd

However the main difference here is that instead of listening in on gossip we instead just search all attestation from the last N
epochs and find if there is a conflicting attestation. Having something that 'waits' for a while is a possible liveness fault, as in the event of a restart a validator would miss an attestation in that particular epoch.

**Comment by nisdas** [comment]
@quangld You can track this issue in #7985 .
