### ISSUE TITLE
Unify gRPC Gateways Into Single, Shared Package

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#8783]
# 💎 Issue

### Background

We have several instaces of gRPC gateways which are essentially duplicated code, all throughout Prysm. We have one in the beacon node, one in the validator, and we should definitely create a shared/gateway package that contains this code in a single place to make it more maintanable.

**Comment by ahadda5** [comment]
Anyone working on this?   
I see the duplicate code and I have questions: 
1)  beacon's code handles dialUnix and  dialTCP.  I guess validator only needs to HTTP-json traffic to the "local" beacon node, unlike the beacon which has to connect and thus support any peer out there
2) what is the Swaggerserver which beacon-chain supports and not validator gRPC gateway. 
3) What is your take on modularity of functions in terms of files. So cors.go is separate in beacon-chain but in the same file in validator/rpc. Which one is more the style here? 
4) There is the main func which runs the beacon server itself. That remains untouched obviously. 

In terms of Strategy to get into a single, shared package
A shared/gateway will be created which will have

- Gateway struct defined
- New func call
- Start func
- Handlers registration 
- Status func
- Stop func

A new variable will be introduced , mainly caller-type (beacon or validator) to handle divergence in code scenarios mentioned above. 
Is that a road plan or am I complicating things?

**Comment by rauljordan** [comment]
Hi @ahadda5 no one is working on this yet. 

1. We should create a general, shared gateway package that can support both
2. The beacon chain RPC is a combination of internal RPC endpoints defined in proto/beacon/rpc/v1 and https://github.com/prysmaticlabs/ethereumapis. The latter has swagger definitions but the former does not. The validator RPC endpoints also do not have swagger definitions
3. It is fine to separate that into files, no preference. It is useful when a file gets way too big and we want to split them up. In general, we should aim to keep files under 200 or 300 loc.
4. No need to differentiate callers if it is a generic, shared package

**Comment by ahadda5** [comment]
> 4. No need to differentiate callers if it is a generic, shared package
How do you handle the fact that the handlers for each gateway is different (validator rpc are auth, wallet, health, account, slashing etc. while beacon's  are  beaconchain, health etc..) .Those are two forks in the code when merged.

**Comment by ahadda5** [comment]
I'm trying to merge beacon and validator gateways (easier to maintain shared lib) and the  obstacles i have are the handlers. 
First the beacon gateway uses remoteCerrt, enableDebugRPCEndpoints  and maxCallRecvMsgSize  in its struct. 
Those are used in the beacon's gateway inhouse dial function which uses the remoteCert and the  MaxCallRcvmsgSize when calling (google.golang) grpc
The validator does a direct use of the  grpc DialOption func with no use of those options. 

Secondly, the handlers are different.  Beacon has a beachon-chain handler, health handler etc, while
validator has its own Auth, wallet, health account handlers, each requiring its own library . When merging the code, we need some caller distinction or a struct/list of handlers to be registered respectively , otherwise how do you handle this ?
