### ISSUE TITLE
Canonical Fetcher is Incorrect

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8955]
# 🐞 Bug Report

### Description

It has been observed by @guybrush  that for some RPC calls the canonical fetcher has been returning incorrect data. It has been marking non-canonical blocks as canonical for a certain period of time before reverting to the correct behaviour after an extended period of time. 

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction

```sh
 curl -s "prysm-mainnet-1:3500/eth/v1alpha1/beacon/blocks?slot=1202976" | jq '.blockContainers[0].canonical'
true
```
https://gist.github.com/guybrush/fa0124420caada884492bedcfa695e55
https://gist.github.com/guybrush/d825a5f4a653a6b86f69ddd807195136

**Comment by guybrush** [comment]
related discord discussions:
- https://discord.com/channels/595666850260713488/746343380900118528/843870617680871474
- https://discord.com/channels/476244492043812875/652609895941799976/847726749668212736

**Comment by 0xKiwi** [comment]
After looking more thoroughly into the problem, it could be related to `updateFinalizedBlockRoots()`. Until the block root is written into the DB we use an in-memory mapping of roots that is shared with forkchoice, but upon finalization we essentially rebuild the canonical roots DB and refer to that instead of the in-memory map. That could explain the sudden change what the beacon node is reporting.

**Comment by rauljordan** [comment]
@nisdas is this fixed by your latest canonical inclusion PR?

**Comment by nisdas** [comment]
Not that PR, it appeared to be a forkchoice bug that @potuz has fixed a while back. We can close this issue
