### ISSUE TITLE
Change SHA256 Library

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#9389]
# 💎 Issue

### Background

@potuz has done some extensive research into the usage of sha256 by eth2 clients. 
https://hackmd.io/@potuz/rJX9iD30u

The summary of the report:
- Most SHA256 libraries are highly optimized to hash large buffers.
- When computing the root of a Merkle tree, the padding block takes as much time as the data block.
- Hardcoding the precomputed scheduled words of the padding block we save 40% of hashing time.

### Description

There is a potential gain of 40% for clients if they do implement this optimization in their respective sha256 libraries. Unfortunately most sha256 libraries are written in assembly, and are specific for different architectures and operating
systems. Changing this to account for all the different architectures + supported instructions will be a non trivial task. 

Prysm currently uses this sha256 library:
https://github.com/minio/sha256-simd

Unfortunately the library currently only supports CPUs with sha extensions and AVX512. It is relevant to mention that most consumer machines do not have sha extensions or AVX512 enabled by default. The earliest release for sha extensions in consumer laptops/desktops was only in the tigerlake release for machines running intel processors. 

The maintainers of the library want to reduce the scope of the library and have removed support for their AVX/SSE asm. Instead CPUs with AVX2 will simply default to the current default go sha256 library. 
https://github.com/minio/sha256-simd/issues/58

To enable this optimization of precomputing the padding, we would either need to fork minio and add it in ourselves or find any other sha256 library that has this feature.

**Comment by potuz** [comment]
My implementation of SSZ + Merkleization + SHA is live in https://github.com/potuz/mammon, the SHA assembly can easily be turned into portable, one header, library as a last resort. It currently supports Intel + AMD SSE/AVX/AVX-2/SHA-ni. It is missing ARM and SHA512 which I cannot test. I modified the assembly from https://github.com/intel/intel-ipsec-mb. Most assembly (at least all in a form that I could read) has been taken from them.  Have you thought about contacting the Intel guys directly? They may be willing to add this, and their library is actively maintained. 

Linking also Chainsafe's implementation https://github.com/ChainSafe/as-sha256/pull/59  https://github.com/ChainSafe/as-sha256/pull/51 

And Nimbus open issue: https://github.com/status-im/nimbus-eth2/issues/2740
You can find some of my newer benchmarks in the latter. 

It should be easy for me to port the SHA assembly as a portable ISO-C or C++ implementation since this would be low mainteinance (currently is not really portable, it only runs on linux and assumes at the very least AVX, which I think we can safely do though). But I wouldn't spend time on the bridge with fastssz, in fact, does this issue belong in prysm or does it belong in fastssz?

**Comment by potuz** [comment]
Closing this as included in #10286 feel free to reopen.
